/**
 * This file was automatically generated by generate-db-types
 * Do not make changes to this file directly
 */

import { Duration } from "date-fns";

type Maybe<T> = T | null;

type PartialProps<T, K extends keyof T = never> = Omit<T, K> & Partial<Pick<T, K>>;

export type AiCompletionLogStatus = "PENDING" | "COMPLETED" | "FAILED";

export const AiCompletionLogStatusValues = [
  "PENDING",
  "COMPLETED",
  "FAILED",
] as AiCompletionLogStatus[];

export type AiCompletionLogType = "PETITION_SUMMARY";

export const AiCompletionLogTypeValues = ["PETITION_SUMMARY"] as AiCompletionLogType[];

export type ContactLocale = "en" | "es" | "ca" | "it" | "pt";

export const ContactLocaleValues = ["en", "es", "ca", "it", "pt"] as ContactLocale[];

export type DocumentProcessingType = "PAYSLIP";

export const DocumentProcessingTypeValues = ["PAYSLIP"] as DocumentProcessingType[];

export type EventSubscriptionType = "PETITION" | "PROFILE";

export const EventSubscriptionTypeValues = ["PETITION", "PROFILE"] as EventSubscriptionType[];

export type FeatureFlagName =
  | "PETITION_SIGNATURE"
  | "HIDE_RECIPIENT_VIEW_CONTENTS"
  | "SKIP_FORWARD_SECURITY"
  | "EXPORT_CUATRECASAS"
  | "REMOVE_WHY_WE_USE_PARALLEL"
  | "ON_BEHALF_OF"
  | "GHOST_LOGIN"
  | "ES_TAX_DOCUMENTS_FIELD"
  | "REMOVE_PARALLEL_BRANDING"
  | "CUSTOM_HOST_UI"
  | "PUBLIC_PETITION_LINK_PREFILL_SECRET_UI"
  | "PETITION_ACCESS_RECIPIENT_URL_FIELD"
  | "AUTO_ANONYMIZE"
  | "TEMPLATE_REPLIES_PREVIEW_URL"
  | "DOW_JONES_KYC"
  | "PUBLIC_PETITION_LINK_PREFILL_DATA"
  | "DOCUSIGN_SANDBOX_PROVIDER"
  | "CLIENT_PORTAL"
  | "PROFILES"
  | "PERMISSION_MANAGEMENT"
  | "CUSTOM_PROPERTIES"
  | "BULK_PETITION_SEND_TASK"
  | "TEMPLATE_REPLIES_CSV_EXPORT_TASK"
  | "SETTING_DELEGATE_ACCESS"
  | "PETITION_SUMMARY"
  | "RECIPIENT_LANG_CA"
  | "RECIPIENT_LANG_IT"
  | "RECIPIENT_LANG_PT"
  | "BACKGROUND_CHECK"
  | "CREATE_PROFILE_TYPE"
  | "PDF_EXPORT_V2";

export const FeatureFlagNameValues = [
  "PETITION_SIGNATURE",
  "HIDE_RECIPIENT_VIEW_CONTENTS",
  "SKIP_FORWARD_SECURITY",
  "EXPORT_CUATRECASAS",
  "REMOVE_WHY_WE_USE_PARALLEL",
  "ON_BEHALF_OF",
  "GHOST_LOGIN",
  "ES_TAX_DOCUMENTS_FIELD",
  "REMOVE_PARALLEL_BRANDING",
  "CUSTOM_HOST_UI",
  "PUBLIC_PETITION_LINK_PREFILL_SECRET_UI",
  "PETITION_ACCESS_RECIPIENT_URL_FIELD",
  "AUTO_ANONYMIZE",
  "TEMPLATE_REPLIES_PREVIEW_URL",
  "DOW_JONES_KYC",
  "PUBLIC_PETITION_LINK_PREFILL_DATA",
  "DOCUSIGN_SANDBOX_PROVIDER",
  "CLIENT_PORTAL",
  "PROFILES",
  "PERMISSION_MANAGEMENT",
  "CUSTOM_PROPERTIES",
  "BULK_PETITION_SEND_TASK",
  "TEMPLATE_REPLIES_CSV_EXPORT_TASK",
  "SETTING_DELEGATE_ACCESS",
  "PETITION_SUMMARY",
  "RECIPIENT_LANG_CA",
  "RECIPIENT_LANG_IT",
  "RECIPIENT_LANG_PT",
  "BACKGROUND_CHECK",
  "CREATE_PROFILE_TYPE",
  "PDF_EXPORT_V2",
] as FeatureFlagName[];

export type IntegrationType =
  | "SIGNATURE"
  | "SSO"
  | "USER_PROVISIONING"
  | "DOW_JONES_KYC"
  | "AI_COMPLETION"
  | "ID_VERIFICATION"
  | "DOCUMENT_PROCESSING"
  | "PROFILE_EXTERNAL_SOURCE"
  | "FILE_EXPORT";

export const IntegrationTypeValues = [
  "SIGNATURE",
  "SSO",
  "USER_PROVISIONING",
  "DOW_JONES_KYC",
  "AI_COMPLETION",
  "ID_VERIFICATION",
  "DOCUMENT_PROCESSING",
  "PROFILE_EXTERNAL_SOURCE",
  "FILE_EXPORT",
] as IntegrationType[];

export type LicenseCodeStatus = "PENDING" | "REDEEMED" | "EXPIRED";

export const LicenseCodeStatusValues = ["PENDING", "REDEEMED", "EXPIRED"] as LicenseCodeStatus[];

export type OrganizationStatus = "DEV" | "DEMO" | "ACTIVE" | "CHURNED" | "ROOT";

export const OrganizationStatusValues = [
  "DEV",
  "DEMO",
  "ACTIVE",
  "CHURNED",
  "ROOT",
] as OrganizationStatus[];

export type OrganizationThemeType = "PDF_DOCUMENT" | "BRAND";

export const OrganizationThemeTypeValues = ["PDF_DOCUMENT", "BRAND"] as OrganizationThemeType[];

export type OrganizationUsageLimitName = "PETITION_SEND" | "SIGNATURIT_SHARED_APIKEY";

export const OrganizationUsageLimitNameValues = [
  "PETITION_SEND",
  "SIGNATURIT_SHARED_APIKEY",
] as OrganizationUsageLimitName[];

export type PetitionAccessStatus = "ACTIVE" | "INACTIVE";

export const PetitionAccessStatusValues = ["ACTIVE", "INACTIVE"] as PetitionAccessStatus[];

export type PetitionAttachmentType = "FRONT" | "ANNEX" | "BACK";

export const PetitionAttachmentTypeValues = ["FRONT", "ANNEX", "BACK"] as PetitionAttachmentType[];

export type PetitionContactNotificationType = "COMMENT_CREATED";

export const PetitionContactNotificationTypeValues = [
  "COMMENT_CREATED",
] as PetitionContactNotificationType[];

export type PetitionEventType =
  | "PETITION_CREATED"
  | "PETITION_COMPLETED"
  | "ACCESS_ACTIVATED"
  | "ACCESS_DEACTIVATED"
  | "ACCESS_OPENED"
  | "MESSAGE_SCHEDULED"
  | "MESSAGE_CANCELLED"
  | "MESSAGE_SENT"
  | "REMINDER_SENT"
  | "REPLY_CREATED"
  | "REPLY_DELETED"
  | "COMMENT_PUBLISHED"
  | "COMMENT_DELETED"
  | "USER_PERMISSION_ADDED"
  | "USER_PERMISSION_REMOVED"
  | "USER_PERMISSION_EDITED"
  | "OWNERSHIP_TRANSFERRED"
  | "PETITION_CLOSED"
  | "PETITION_CLOSED_NOTIFIED"
  | "PETITION_REOPENED"
  | "SIGNATURE_STARTED"
  | "SIGNATURE_COMPLETED"
  | "SIGNATURE_CANCELLED"
  | "ACCESS_DELEGATED"
  | "REPLY_UPDATED"
  | "GROUP_PERMISSION_ADDED"
  | "GROUP_PERMISSION_EDITED"
  | "GROUP_PERMISSION_REMOVED"
  | "TEMPLATE_USED"
  | "PETITION_CLONED"
  | "PETITION_DELETED"
  | "REMINDERS_OPT_OUT"
  | "ACCESS_ACTIVATED_FROM_PUBLIC_PETITION_LINK"
  | "RECIPIENT_SIGNED"
  | "PETITION_MESSAGE_BOUNCED"
  | "PETITION_REMINDER_BOUNCED"
  | "SIGNATURE_REMINDER"
  | "SIGNATURE_OPENED"
  | "PETITION_ANONYMIZED"
  | "REPLY_STATUS_CHANGED"
  | "PROFILE_ASSOCIATED"
  | "PROFILE_DISASSOCIATED"
  | "SIGNATURE_DELIVERED"
  | "PETITION_TAGGED"
  | "PETITION_UNTAGGED"
  | "CONTACTLESS_ACCESS_USED";

export const PetitionEventTypeValues = [
  "PETITION_CREATED",
  "PETITION_COMPLETED",
  "ACCESS_ACTIVATED",
  "ACCESS_DEACTIVATED",
  "ACCESS_OPENED",
  "MESSAGE_SCHEDULED",
  "MESSAGE_CANCELLED",
  "MESSAGE_SENT",
  "REMINDER_SENT",
  "REPLY_CREATED",
  "REPLY_DELETED",
  "COMMENT_PUBLISHED",
  "COMMENT_DELETED",
  "USER_PERMISSION_ADDED",
  "USER_PERMISSION_REMOVED",
  "USER_PERMISSION_EDITED",
  "OWNERSHIP_TRANSFERRED",
  "PETITION_CLOSED",
  "PETITION_CLOSED_NOTIFIED",
  "PETITION_REOPENED",
  "SIGNATURE_STARTED",
  "SIGNATURE_COMPLETED",
  "SIGNATURE_CANCELLED",
  "ACCESS_DELEGATED",
  "REPLY_UPDATED",
  "GROUP_PERMISSION_ADDED",
  "GROUP_PERMISSION_EDITED",
  "GROUP_PERMISSION_REMOVED",
  "TEMPLATE_USED",
  "PETITION_CLONED",
  "PETITION_DELETED",
  "REMINDERS_OPT_OUT",
  "ACCESS_ACTIVATED_FROM_PUBLIC_PETITION_LINK",
  "RECIPIENT_SIGNED",
  "PETITION_MESSAGE_BOUNCED",
  "PETITION_REMINDER_BOUNCED",
  "SIGNATURE_REMINDER",
  "SIGNATURE_OPENED",
  "PETITION_ANONYMIZED",
  "REPLY_STATUS_CHANGED",
  "PROFILE_ASSOCIATED",
  "PROFILE_DISASSOCIATED",
  "SIGNATURE_DELIVERED",
  "PETITION_TAGGED",
  "PETITION_UNTAGGED",
  "CONTACTLESS_ACCESS_USED",
] as PetitionEventType[];

export type PetitionFieldReplyStatus = "PENDING" | "REJECTED" | "APPROVED";

export const PetitionFieldReplyStatusValues = [
  "PENDING",
  "REJECTED",
  "APPROVED",
] as PetitionFieldReplyStatus[];

export type PetitionFieldType =
  | "TEXT"
  | "FILE_UPLOAD"
  | "HEADING"
  | "SELECT"
  | "DYNAMIC_SELECT"
  | "SHORT_TEXT"
  | "CHECKBOX"
  | "NUMBER"
  | "PHONE"
  | "DATE"
  | "ES_TAX_DOCUMENTS"
  | "DOW_JONES_KYC"
  | "DATE_TIME"
  | "FIELD_GROUP"
  | "BACKGROUND_CHECK"
  | "ID_VERIFICATION";

export const PetitionFieldTypeValues = [
  "TEXT",
  "FILE_UPLOAD",
  "HEADING",
  "SELECT",
  "DYNAMIC_SELECT",
  "SHORT_TEXT",
  "CHECKBOX",
  "NUMBER",
  "PHONE",
  "DATE",
  "ES_TAX_DOCUMENTS",
  "DOW_JONES_KYC",
  "DATE_TIME",
  "FIELD_GROUP",
  "BACKGROUND_CHECK",
  "ID_VERIFICATION",
] as PetitionFieldType[];

export type PetitionMessageStatus = "SCHEDULED" | "CANCELLED" | "PROCESSING" | "PROCESSED";

export const PetitionMessageStatusValues = [
  "SCHEDULED",
  "CANCELLED",
  "PROCESSING",
  "PROCESSED",
] as PetitionMessageStatus[];

export type PetitionPermissionType = "OWNER" | "WRITE" | "READ";

export const PetitionPermissionTypeValues = ["OWNER", "WRITE", "READ"] as PetitionPermissionType[];

export type PetitionReminderStatus = "PROCESSING" | "PROCESSED" | "ERROR";

export const PetitionReminderStatusValues = [
  "PROCESSING",
  "PROCESSED",
  "ERROR",
] as PetitionReminderStatus[];

export type PetitionReminderType = "MANUAL" | "AUTOMATIC";

export const PetitionReminderTypeValues = ["MANUAL", "AUTOMATIC"] as PetitionReminderType[];

export type PetitionSignatureCancelReason =
  | "CANCELLED_BY_USER"
  | "DECLINED_BY_SIGNER"
  | "REQUEST_ERROR"
  | "REQUEST_RESTARTED";

export const PetitionSignatureCancelReasonValues = [
  "CANCELLED_BY_USER",
  "DECLINED_BY_SIGNER",
  "REQUEST_ERROR",
  "REQUEST_RESTARTED",
] as PetitionSignatureCancelReason[];

export type PetitionSignatureStatus =
  | "ENQUEUED"
  | "PROCESSING"
  | "PROCESSED"
  | "CANCELLING"
  | "CANCELLED"
  | "COMPLETED";

export const PetitionSignatureStatusValues = [
  "ENQUEUED",
  "PROCESSING",
  "PROCESSED",
  "CANCELLING",
  "CANCELLED",
  "COMPLETED",
] as PetitionSignatureStatus[];

export type PetitionStatus = "DRAFT" | "PENDING" | "COMPLETED" | "CLOSED";

export const PetitionStatusValues = ["DRAFT", "PENDING", "COMPLETED", "CLOSED"] as PetitionStatus[];

export type PetitionUserNotificationType =
  | "COMMENT_CREATED"
  | "PETITION_COMPLETED"
  | "SIGNATURE_COMPLETED"
  | "SIGNATURE_CANCELLED"
  | "PETITION_SHARED"
  | "MESSAGE_EMAIL_BOUNCED"
  | "REMINDERS_OPT_OUT"
  | "REMINDER_EMAIL_BOUNCED"
  | "ACCESS_ACTIVATED_FROM_PUBLIC_PETITION_LINK";

export const PetitionUserNotificationTypeValues = [
  "COMMENT_CREATED",
  "PETITION_COMPLETED",
  "SIGNATURE_COMPLETED",
  "SIGNATURE_CANCELLED",
  "PETITION_SHARED",
  "MESSAGE_EMAIL_BOUNCED",
  "REMINDERS_OPT_OUT",
  "REMINDER_EMAIL_BOUNCED",
  "ACCESS_ACTIVATED_FROM_PUBLIC_PETITION_LINK",
] as PetitionUserNotificationType[];

export type ProfileEventType =
  | "PROFILE_CREATED"
  | "PROFILE_FIELD_VALUE_UPDATED"
  | "PROFILE_FIELD_FILE_ADDED"
  | "PROFILE_FIELD_FILE_REMOVED"
  | "PROFILE_FIELD_EXPIRY_UPDATED"
  | "PETITION_ASSOCIATED"
  | "PETITION_DISASSOCIATED"
  | "PROFILE_CLOSED"
  | "PROFILE_SCHEDULED_FOR_DELETION"
  | "PROFILE_REOPENED"
  | "PROFILE_ANONYMIZED"
  | "PROFILE_UPDATED"
  | "PROFILE_RELATIONSHIP_CREATED"
  | "PROFILE_RELATIONSHIP_REMOVED";

export const ProfileEventTypeValues = [
  "PROFILE_CREATED",
  "PROFILE_FIELD_VALUE_UPDATED",
  "PROFILE_FIELD_FILE_ADDED",
  "PROFILE_FIELD_FILE_REMOVED",
  "PROFILE_FIELD_EXPIRY_UPDATED",
  "PETITION_ASSOCIATED",
  "PETITION_DISASSOCIATED",
  "PROFILE_CLOSED",
  "PROFILE_SCHEDULED_FOR_DELETION",
  "PROFILE_REOPENED",
  "PROFILE_ANONYMIZED",
  "PROFILE_UPDATED",
  "PROFILE_RELATIONSHIP_CREATED",
  "PROFILE_RELATIONSHIP_REMOVED",
] as ProfileEventType[];

export type ProfileRelationshipTypeDirection = "LEFT_RIGHT" | "RIGHT_LEFT";

export const ProfileRelationshipTypeDirectionValues = [
  "LEFT_RIGHT",
  "RIGHT_LEFT",
] as ProfileRelationshipTypeDirection[];

export type ProfileStatus = "OPEN" | "CLOSED" | "DELETION_SCHEDULED";

export const ProfileStatusValues = ["OPEN", "CLOSED", "DELETION_SCHEDULED"] as ProfileStatus[];

export type ProfileTypeFieldPermissionType = "HIDDEN" | "READ" | "WRITE";

export const ProfileTypeFieldPermissionTypeValues = [
  "HIDDEN",
  "READ",
  "WRITE",
] as ProfileTypeFieldPermissionType[];

export type ProfileTypeFieldType =
  | "TEXT"
  | "SHORT_TEXT"
  | "FILE"
  | "DATE"
  | "PHONE"
  | "NUMBER"
  | "SELECT"
  | "BACKGROUND_CHECK"
  | "CHECKBOX";

export const ProfileTypeFieldTypeValues = [
  "TEXT",
  "SHORT_TEXT",
  "FILE",
  "DATE",
  "PHONE",
  "NUMBER",
  "SELECT",
  "BACKGROUND_CHECK",
  "CHECKBOX",
] as ProfileTypeFieldType[];

export type ProfileTypeStandardType = "INDIVIDUAL" | "LEGAL_ENTITY" | "CONTRACT";

export const ProfileTypeStandardTypeValues = [
  "INDIVIDUAL",
  "LEGAL_ENTITY",
  "CONTRACT",
] as ProfileTypeStandardType[];

export type SystemEventType =
  | "USER_CREATED"
  | "USER_LOGGED_IN"
  | "EMAIL_OPENED"
  | "EMAIL_VERIFIED"
  | "INVITE_SENT"
  | "ORGANIZATION_LIMIT_REACHED";

export const SystemEventTypeValues = [
  "USER_CREATED",
  "USER_LOGGED_IN",
  "EMAIL_OPENED",
  "EMAIL_VERIFIED",
  "INVITE_SENT",
  "ORGANIZATION_LIMIT_REACHED",
] as SystemEventType[];

export type TaskName =
  | "PRINT_PDF"
  | "EXPORT_REPLIES"
  | "EXPORT_EXCEL"
  | "TEMPLATE_REPLIES_REPORT"
  | "TEMPLATE_STATS_REPORT"
  | "DOW_JONES_PROFILE_DOWNLOAD"
  | "TEMPLATES_OVERVIEW_REPORT"
  | "BANKFLIP_SESSION_COMPLETED"
  | "BULK_PETITION_SEND"
  | "TEMPLATE_REPLIES_CSV_EXPORT"
  | "PETITION_SUMMARY"
  | "BACKGROUND_CHECK_PROFILE_PDF"
  | "PETITION_SHARING"
  | "PROFILE_NAME_PATTERN_UPDATED"
  | "ID_VERIFICATION_SESSION_COMPLETED"
  | "FILE_EXPORT"
  | "CLOSE_PETITIONS";

export const TaskNameValues = [
  "PRINT_PDF",
  "EXPORT_REPLIES",
  "EXPORT_EXCEL",
  "TEMPLATE_REPLIES_REPORT",
  "TEMPLATE_STATS_REPORT",
  "DOW_JONES_PROFILE_DOWNLOAD",
  "TEMPLATES_OVERVIEW_REPORT",
  "BANKFLIP_SESSION_COMPLETED",
  "BULK_PETITION_SEND",
  "TEMPLATE_REPLIES_CSV_EXPORT",
  "PETITION_SUMMARY",
  "BACKGROUND_CHECK_PROFILE_PDF",
  "PETITION_SHARING",
  "PROFILE_NAME_PATTERN_UPDATED",
  "ID_VERIFICATION_SESSION_COMPLETED",
  "FILE_EXPORT",
  "CLOSE_PETITIONS",
] as TaskName[];

export type TaskStatus = "ENQUEUED" | "PROCESSING" | "COMPLETED" | "FAILED";

export const TaskStatusValues = ["ENQUEUED", "PROCESSING", "COMPLETED", "FAILED"] as TaskStatus[];

export type UserGroupPermissionEffect = "GRANT" | "DENY";

export const UserGroupPermissionEffectValues = ["GRANT", "DENY"] as UserGroupPermissionEffect[];

export type UserGroupPermissionName =
  | "SUPERADMIN"
  | "REPORTS:OVERVIEW"
  | "REPORTS:TEMPLATE_STATISTICS"
  | "REPORTS:TEMPLATE_REPLIES"
  | "PROFILES:DELETE_PROFILES"
  | "PROFILES:DELETE_PERMANENTLY_PROFILES"
  | "PROFILE_TYPES:CRUD_PROFILE_TYPES"
  | "INTEGRATIONS:CRUD_INTEGRATIONS"
  | "USERS:CRUD_USERS"
  | "USERS:GHOST_LOGIN"
  | "TEAMS:CRUD_TEAMS"
  | "ORG_SETTINGS"
  | "CONTACTS:DELETE_CONTACTS"
  | "PETITIONS:SEND_ON_BEHALF"
  | "PETITIONS:CHANGE_PATH"
  | "PETITIONS:CREATE_TEMPLATES"
  | "INTEGRATIONS:CRUD_API"
  | "PROFILES:SUBSCRIBE_PROFILES"
  | "PETITIONS:CREATE_PETITIONS"
  | "PROFILES:CREATE_PROFILES"
  | "PROFILES:CLOSE_PROFILES"
  | "PROFILES:LIST_PROFILES"
  | "PROFILE_ALERTS:LIST_ALERTS"
  | "CONTACTS:LIST_CONTACTS"
  | "USERS:LIST_USERS"
  | "TEAMS:LIST_TEAMS"
  | "TAGS:CREATE_TAGS"
  | "TAGS:UPDATE_TAGS"
  | "TAGS:DELETE_TAGS"
  | "TEAMS:READ_PERMISSIONS"
  | "TEAMS:UPDATE_PERMISSIONS"
  | "PETITIONS:LIST_PUBLIC_TEMPLATES";

export const UserGroupPermissionNameValues = [
  "SUPERADMIN",
  "REPORTS:OVERVIEW",
  "REPORTS:TEMPLATE_STATISTICS",
  "REPORTS:TEMPLATE_REPLIES",
  "PROFILES:DELETE_PROFILES",
  "PROFILES:DELETE_PERMANENTLY_PROFILES",
  "PROFILE_TYPES:CRUD_PROFILE_TYPES",
  "INTEGRATIONS:CRUD_INTEGRATIONS",
  "USERS:CRUD_USERS",
  "USERS:GHOST_LOGIN",
  "TEAMS:CRUD_TEAMS",
  "ORG_SETTINGS",
  "CONTACTS:DELETE_CONTACTS",
  "PETITIONS:SEND_ON_BEHALF",
  "PETITIONS:CHANGE_PATH",
  "PETITIONS:CREATE_TEMPLATES",
  "INTEGRATIONS:CRUD_API",
  "PROFILES:SUBSCRIBE_PROFILES",
  "PETITIONS:CREATE_PETITIONS",
  "PROFILES:CREATE_PROFILES",
  "PROFILES:CLOSE_PROFILES",
  "PROFILES:LIST_PROFILES",
  "PROFILE_ALERTS:LIST_ALERTS",
  "CONTACTS:LIST_CONTACTS",
  "USERS:LIST_USERS",
  "TEAMS:LIST_TEAMS",
  "TAGS:CREATE_TAGS",
  "TAGS:UPDATE_TAGS",
  "TAGS:DELETE_TAGS",
  "TEAMS:READ_PERMISSIONS",
  "TEAMS:UPDATE_PERMISSIONS",
  "PETITIONS:LIST_PUBLIC_TEMPLATES",
] as UserGroupPermissionName[];

export type UserGroupType = "NORMAL" | "ALL_USERS" | "INITIAL";

export const UserGroupTypeValues = ["NORMAL", "ALL_USERS", "INITIAL"] as UserGroupType[];

export type UserLocale = "en" | "es";

export const UserLocaleValues = ["en", "es"] as UserLocale[];

export type UserStatus = "ACTIVE" | "INACTIVE" | "ON_HOLD";

export const UserStatusValues = ["ACTIVE", "INACTIVE", "ON_HOLD"] as UserStatus[];

export interface TableTypes {
  ai_completion_log: AiCompletionLog;
  contact: Contact;
  contact_authentication: ContactAuthentication;
  contact_authentication_request: ContactAuthenticationRequest;
  document_processing_log: DocumentProcessingLog;
  email_attachment: EmailAttachment;
  email_event: EmailEvent;
  email_log: EmailLog;
  event_subscription: EventSubscription;
  event_subscription_signature_key: EventSubscriptionSignatureKey;
  feature_flag: FeatureFlag;
  feature_flag_override: FeatureFlagOverride;
  file_export_log: FileExportLog;
  file_upload: FileUpload;
  license_code: LicenseCode;
  organization: Organization;
  organization_theme: OrganizationTheme;
  organization_usage_limit: OrganizationUsageLimit;
  org_integration: OrgIntegration;
  petition: Petition;
  petition_access: PetitionAccess;
  petition_attachment: PetitionAttachment;
  petition_contact_notification: PetitionContactNotification;
  petition_event: PetitionEvent;
  petition_field: PetitionField;
  petition_field_attachment: PetitionFieldAttachment;
  petition_field_comment: PetitionFieldComment;
  petition_field_group_relationship: PetitionFieldGroupRelationship;
  petition_field_reply: PetitionFieldReply;
  petition_list_view: PetitionListView;
  petition_message: PetitionMessage;
  petition_permission: PetitionPermission;
  petition_profile: PetitionProfile;
  petition_reminder: PetitionReminder;
  petition_signature_request: PetitionSignatureRequest;
  petition_tag: PetitionTag;
  petition_user_notification: PetitionUserNotification;
  profile: Profile;
  profile_event: ProfileEvent;
  profile_external_source_entity: ProfileExternalSourceEntity;
  profile_field_file: ProfileFieldFile;
  profile_field_value: ProfileFieldValue;
  profile_relationship: ProfileRelationship;
  profile_relationship_type: ProfileRelationshipType;
  profile_relationship_type_allowed_profile_type: ProfileRelationshipTypeAllowedProfileType;
  profile_subscription: ProfileSubscription;
  profile_type: ProfileType;
  profile_type_field: ProfileTypeField;
  profile_type_field_permission: ProfileTypeFieldPermission;
  public_file_upload: PublicFileUpload;
  public_petition_link: PublicPetitionLink;
  public_petition_link_prefill_data: PublicPetitionLinkPrefillData;
  system_event: SystemEvent;
  tag: Tag;
  task: Task;
  template_default_permission: TemplateDefaultPermission;
  temporary_file: TemporaryFile;
  user: User;
  user_authentication_token: UserAuthenticationToken;
  user_data: UserData;
  user_delegate: UserDelegate;
  user_group: UserGroup;
  user_group_member: UserGroupMember;
  user_group_permission: UserGroupPermission;
  user_petition_event_log: UserPetitionEventLog;
  user_profile_event_log: UserProfileEventLog;
}

export interface TableCreateTypes {
  ai_completion_log: CreateAiCompletionLog;
  contact: CreateContact;
  contact_authentication: CreateContactAuthentication;
  contact_authentication_request: CreateContactAuthenticationRequest;
  document_processing_log: CreateDocumentProcessingLog;
  email_attachment: CreateEmailAttachment;
  email_event: CreateEmailEvent;
  email_log: CreateEmailLog;
  event_subscription: CreateEventSubscription;
  event_subscription_signature_key: CreateEventSubscriptionSignatureKey;
  feature_flag: CreateFeatureFlag;
  feature_flag_override: CreateFeatureFlagOverride;
  file_export_log: CreateFileExportLog;
  file_upload: CreateFileUpload;
  license_code: CreateLicenseCode;
  organization: CreateOrganization;
  organization_theme: CreateOrganizationTheme;
  organization_usage_limit: CreateOrganizationUsageLimit;
  org_integration: CreateOrgIntegration;
  petition: CreatePetition;
  petition_access: CreatePetitionAccess;
  petition_attachment: CreatePetitionAttachment;
  petition_contact_notification: CreatePetitionContactNotification;
  petition_event: CreatePetitionEvent;
  petition_field: CreatePetitionField;
  petition_field_attachment: CreatePetitionFieldAttachment;
  petition_field_comment: CreatePetitionFieldComment;
  petition_field_group_relationship: CreatePetitionFieldGroupRelationship;
  petition_field_reply: CreatePetitionFieldReply;
  petition_list_view: CreatePetitionListView;
  petition_message: CreatePetitionMessage;
  petition_permission: CreatePetitionPermission;
  petition_profile: CreatePetitionProfile;
  petition_reminder: CreatePetitionReminder;
  petition_signature_request: CreatePetitionSignatureRequest;
  petition_tag: CreatePetitionTag;
  petition_user_notification: CreatePetitionUserNotification;
  profile: CreateProfile;
  profile_event: CreateProfileEvent;
  profile_external_source_entity: CreateProfileExternalSourceEntity;
  profile_field_file: CreateProfileFieldFile;
  profile_field_value: CreateProfileFieldValue;
  profile_relationship: CreateProfileRelationship;
  profile_relationship_type: CreateProfileRelationshipType;
  profile_relationship_type_allowed_profile_type: CreateProfileRelationshipTypeAllowedProfileType;
  profile_subscription: CreateProfileSubscription;
  profile_type: CreateProfileType;
  profile_type_field: CreateProfileTypeField;
  profile_type_field_permission: CreateProfileTypeFieldPermission;
  public_file_upload: CreatePublicFileUpload;
  public_petition_link: CreatePublicPetitionLink;
  public_petition_link_prefill_data: CreatePublicPetitionLinkPrefillData;
  system_event: CreateSystemEvent;
  tag: CreateTag;
  task: CreateTask;
  template_default_permission: CreateTemplateDefaultPermission;
  temporary_file: CreateTemporaryFile;
  user: CreateUser;
  user_authentication_token: CreateUserAuthenticationToken;
  user_data: CreateUserData;
  user_delegate: CreateUserDelegate;
  user_group: CreateUserGroup;
  user_group_member: CreateUserGroupMember;
  user_group_permission: CreateUserGroupPermission;
  user_petition_event_log: CreateUserPetitionEventLog;
  user_profile_event_log: CreateUserProfileEventLog;
}

export interface TablePrimaryKeys {
  ai_completion_log: "id";
  contact: "id";
  contact_authentication: "id";
  contact_authentication_request: "id";
  document_processing_log: "id";
  email_attachment: "id";
  email_event: "id";
  email_log: "id";
  event_subscription: "id";
  event_subscription_signature_key: "id";
  feature_flag: "id";
  feature_flag_override: "id";
  file_export_log: "id";
  file_upload: "id";
  license_code: "id";
  organization: "id";
  organization_theme: "id";
  organization_usage_limit: "id";
  org_integration: "id";
  petition: "id";
  petition_access: "id";
  petition_attachment: "id";
  petition_contact_notification: "id";
  petition_event: "id";
  petition_field: "id";
  petition_field_attachment: "id";
  petition_field_comment: "id";
  petition_field_group_relationship: "id";
  petition_field_reply: "id";
  petition_list_view: "id";
  petition_message: "id";
  petition_permission: "id";
  petition_profile: "id";
  petition_reminder: "id";
  petition_signature_request: "id";
  petition_tag: "id";
  petition_user_notification: "id";
  profile: "id";
  profile_event: "id";
  profile_external_source_entity: "id";
  profile_field_file: "id";
  profile_field_value: "id";
  profile_relationship: "id";
  profile_relationship_type: "id";
  profile_relationship_type_allowed_profile_type: "id";
  profile_subscription: "id";
  profile_type: "id";
  profile_type_field: "id";
  profile_type_field_permission: "id";
  public_file_upload: "id";
  public_petition_link: "id";
  public_petition_link_prefill_data: "id";
  system_event: "id";
  tag: "id";
  task: "id";
  template_default_permission: "id";
  temporary_file: "id";
  user: "id";
  user_authentication_token: "id";
  user_data: "id";
  user_delegate: "id";
  user_group: "id";
  user_group_member: "id";
  user_group_permission: "id";
  user_petition_event_log: "id";
  user_profile_event_log: "id";
}

export interface AiCompletionLog {
  id: number; // int4
  integration_id: number; // int4
  type: AiCompletionLogType; // ai_completion_log_type
  status: AiCompletionLogStatus; // ai_completion_log_status
  request_params: any; // jsonb
  raw_response: Maybe<any>; // jsonb
  completion: Maybe<string>; // text
  error: Maybe<any>; // jsonb
  request_tokens: Maybe<number>; // int4
  response_tokens: Maybe<number>; // int4
  cost: Maybe<string>; // varchar
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deprecated_at: Maybe<Date>; // timestamptz
  request_duration_ms: Maybe<number>; // int4
}

export type CreateAiCompletionLog = PartialProps<
  Omit<AiCompletionLog, "id">,
  | "status"
  | "raw_response"
  | "completion"
  | "error"
  | "request_tokens"
  | "response_tokens"
  | "cost"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deprecated_at"
  | "request_duration_ms"
>;

export interface Contact {
  id: number; // int4
  email: string; // varchar
  first_name: string; // varchar
  last_name: Maybe<string>; // varchar
  org_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  last_email_bounced: boolean; // bool
  anonymized_at: Maybe<Date>; // timestamptz
}

export type CreateContact = PartialProps<
  Omit<Contact, "id">,
  | "last_name"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "last_email_bounced"
  | "anonymized_at"
>;

export interface ContactAuthentication {
  id: number; // int4
  contact_id: number; // int4
  cookie_value_hash: string; // varchar
  access_log: any; // jsonb
}

export type CreateContactAuthentication = PartialProps<
  Omit<ContactAuthentication, "id">,
  "access_log"
>;

export interface ContactAuthenticationRequest {
  id: number; // int4
  petition_access_id: number; // int4
  token_hash: string; // varchar
  code: string; // varchar
  remaining_attempts: number; // int4
  email_log_id: Maybe<number>; // int4
  ip: Maybe<string>; // varchar
  user_agent: Maybe<string>; // varchar
  expires_at: Date; // timestamptz
  contact_first_name: Maybe<string>; // text
  contact_last_name: Maybe<string>; // text
  contact_email: Maybe<string>; // text
}

export type CreateContactAuthenticationRequest = PartialProps<
  Omit<ContactAuthenticationRequest, "id">,
  | "email_log_id"
  | "ip"
  | "user_agent"
  | "contact_first_name"
  | "contact_last_name"
  | "contact_email"
>;

export interface DocumentProcessingLog {
  id: number; // int4
  external_id: Maybe<string>; // varchar
  integration_id: number; // int4
  file_upload_id: number; // int4
  document_type: DocumentProcessingType; // document_processing_type
  raw_result: Maybe<any>; // jsonb
  error: Maybe<any>; // jsonb
  metadata: any; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
}

export type CreateDocumentProcessingLog = PartialProps<
  Omit<DocumentProcessingLog, "id">,
  | "external_id"
  | "raw_result"
  | "error"
  | "metadata"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
>;

export interface EmailAttachment {
  id: number; // int4
  email_log_id: number; // int4
  temporary_file_id: number; // int4
}

export type CreateEmailAttachment = PartialProps<Omit<EmailAttachment, "id">>;

export interface EmailEvent {
  id: number; // int4
  email_log_id: number; // int4
  event: string; // varchar
  payload: string; // text
  created_at: Date; // timestamptz
}

export type CreateEmailEvent = PartialProps<Omit<EmailEvent, "id">, "created_at">;

export interface EmailLog {
  id: number; // int4
  to: string; // text
  from: string; // text
  subject: string; // text
  text: string; // text
  html: string; // text
  track_opens: boolean; // bool
  created_at: Date; // timestamptz
  created_from: string; // text
  sent_at: Maybe<Date>; // timestamptz
  response: Maybe<string>; // text
  external_id: Maybe<string>; // varchar
  reply_to: Maybe<string>; // text
  anonymized_at: Maybe<Date>; // timestamptz
  processed_at: Maybe<Date>; // timestamptz
  processed_by: Maybe<string>; // varchar
}

export type CreateEmailLog = PartialProps<
  Omit<EmailLog, "id">,
  | "track_opens"
  | "created_at"
  | "sent_at"
  | "response"
  | "external_id"
  | "reply_to"
  | "anonymized_at"
  | "processed_at"
  | "processed_by"
>;

export interface EventSubscription {
  id: number; // int4
  type: EventSubscriptionType; // event_subscription_type
  user_id: number; // int4
  name: Maybe<string>; // varchar
  endpoint: string; // varchar
  event_types: Maybe<any>; // jsonb
  is_enabled: boolean; // bool
  is_failing: boolean; // bool
  from_template_id: Maybe<number>; // int4
  from_template_field_ids: Maybe<number[]>; // int4[]
  from_profile_type_id: Maybe<number>; // int4
  from_profile_type_field_ids: Maybe<number[]>; // int4[]
  error_log: any; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateEventSubscription = PartialProps<
  Omit<EventSubscription, "id">,
  | "name"
  | "event_types"
  | "is_enabled"
  | "is_failing"
  | "from_template_id"
  | "from_template_field_ids"
  | "from_profile_type_id"
  | "from_profile_type_field_ids"
  | "error_log"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface EventSubscriptionSignatureKey {
  id: number; // int4
  event_subscription_id: number; // int4
  public_key: string; // text
  private_key: string; // text
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateEventSubscriptionSignatureKey = PartialProps<
  Omit<EventSubscriptionSignatureKey, "id">,
  "created_at" | "created_by" | "deleted_at" | "deleted_by"
>;

export interface FeatureFlag {
  id: number; // int4
  name: FeatureFlagName; // feature_flag_name
  default_value: boolean; // bool
}

export type CreateFeatureFlag = PartialProps<Omit<FeatureFlag, "id">, "default_value">;

export interface FeatureFlagOverride {
  id: number; // int4
  feature_flag_name: FeatureFlagName; // feature_flag_name
  org_id: Maybe<number>; // int4
  user_id: Maybe<number>; // int4
  value: boolean; // bool
}

export type CreateFeatureFlagOverride = PartialProps<
  Omit<FeatureFlagOverride, "id">,
  "org_id" | "user_id"
>;

export interface FileExportLog {
  id: number; // int4
  integration_id: number; // int4
  json_export: any; // jsonb
  created_by_user_id: number; // int4
  request_log: any; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
}

export type CreateFileExportLog = PartialProps<
  Omit<FileExportLog, "id">,
  "request_log" | "created_at" | "created_by" | "updated_at" | "updated_by"
>;

export interface FileUpload {
  id: number; // int4
  path: string; // varchar
  filename: string; // varchar
  size: string; // int8
  content_type: string; // varchar
  upload_complete: boolean; // bool
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  file_deleted_at: Maybe<Date>; // timestamptz
  password: Maybe<string>; // varchar
}

export type CreateFileUpload = PartialProps<
  Omit<FileUpload, "id">,
  | "upload_complete"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "file_deleted_at"
  | "password"
>;

export interface LicenseCode {
  id: number; // int4
  source: string; // varchar
  code: string; // varchar
  details: any; // jsonb
  status: LicenseCodeStatus; // license_code_status
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
}

export type CreateLicenseCode = PartialProps<
  Omit<LicenseCode, "id">,
  "details" | "status" | "created_at" | "created_by" | "updated_at" | "updated_by"
>;

export interface Organization {
  id: number; // int4
  name: string; // varchar
  status: OrganizationStatus; // organization_status
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  custom_host: Maybe<string>; // varchar
  custom_email_from: Maybe<string>; // varchar
  logo_public_file_id: Maybe<number>; // int4
  usage_details: Maybe<any>; // jsonb
  icon_public_file_id: Maybe<number>; // int4
  appsumo_license: Maybe<any>; // jsonb
  anonymize_petitions_after_months: Maybe<number>; // int4
  default_timezone: string; // varchar
  last_profile_digest_at: Maybe<Date>; // timestamptz
}

export type CreateOrganization = PartialProps<
  Omit<Organization, "id">,
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "custom_host"
  | "custom_email_from"
  | "logo_public_file_id"
  | "usage_details"
  | "icon_public_file_id"
  | "appsumo_license"
  | "anonymize_petitions_after_months"
  | "default_timezone"
  | "last_profile_digest_at"
>;

export interface OrganizationTheme {
  id: number; // int4
  org_id: number; // int4
  name: string; // varchar
  type: OrganizationThemeType; // organization_theme_type
  is_default: boolean; // bool
  data: any; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateOrganizationTheme = PartialProps<
  Omit<OrganizationTheme, "id">,
  | "is_default"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface OrganizationUsageLimit {
  id: number; // int4
  org_id: number; // int4
  limit_name: OrganizationUsageLimitName; // organization_usage_limit_name
  limit: number; // numeric
  used: number; // numeric
  period: Duration; // interval
  period_start_date: Date; // timestamptz
  period_end_date: Maybe<Date>; // timestamptz
  cycle_number: number; // int4
}

export type CreateOrganizationUsageLimit = PartialProps<
  Omit<OrganizationUsageLimit, "id">,
  "used" | "period_start_date" | "period_end_date" | "cycle_number"
>;

export interface OrgIntegration {
  id: number; // int4
  org_id: number; // int4
  type: IntegrationType; // integration_type
  provider: string; // varchar
  settings: Maybe<any>; // jsonb
  is_enabled: boolean; // bool
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  is_default: boolean; // bool
  name: string; // varchar
  invalid_credentials: boolean; // bool
}

export type CreateOrgIntegration = PartialProps<
  Omit<OrgIntegration, "id">,
  | "settings"
  | "is_enabled"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "is_default"
  | "invalid_credentials"
>;

export interface Petition {
  id: number; // int4
  org_id: number; // int4
  name: Maybe<string>; // varchar
  custom_ref: Maybe<string>; // varchar
  is_template: boolean; // bool
  status: Maybe<PetitionStatus>; // petition_status
  deadline: Maybe<Date>; // timestamptz
  email_subject: Maybe<string>; // varchar
  email_body: Maybe<string>; // text
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  reminders_config: Maybe<any>; // jsonb
  template_description: Maybe<string>; // text
  template_public: boolean; // bool
  from_template_id: Maybe<number>; // int4
  signature_config: Maybe<any>; // jsonb
  hide_recipient_view_contents: boolean; // bool
  skip_forward_security: boolean; // bool
  public_metadata: Maybe<any>; // jsonb
  from_public_petition_link_id: Maybe<number>; // int4
  custom_properties: any; // jsonb
  restricted_by_user_id: Maybe<number>; // int4
  restricted_at: Maybe<Date>; // timestamptz
  restricted_password_hash: Maybe<string>; // varchar
  restricted_password_salt: Maybe<string>; // varchar
  credits_used: number; // int4
  closing_email_body: Maybe<string>; // text
  is_completing_message_enabled: boolean; // bool
  completing_message_subject: Maybe<string>; // text
  completing_message_body: Maybe<string>; // text
  anonymized_at: Maybe<Date>; // timestamptz
  metadata: any; // jsonb
  closed_at: Maybe<Date>; // timestamptz
  anonymize_after_months: Maybe<number>; // int4
  anonymize_purpose: Maybe<string>; // text
  document_organization_theme_id: number; // int4
  path: string; // text
  default_path: string; // text
  latest_signature_status: Maybe<string>; // varchar
  send_on_behalf_user_id: Maybe<number>; // int4
  recipient_locale: ContactLocale; // contact_locale
  last_activity_at: Maybe<Date>; // timestamptz
  last_recipient_activity_at: Maybe<Date>; // timestamptz
  variables: any; // jsonb
  enable_delegate_access: boolean; // bool
  last_change_at: Date; // timestamptz
  summary_config: Maybe<any>; // jsonb
  summary_ai_completion_log_id: Maybe<number>; // int4
  custom_lists: Maybe<any>; // jsonb
  enable_interaction_with_recipients: boolean; // bool
  enable_review_flow: boolean; // bool
  enable_document_generation: boolean; // bool
  automatic_numbering_config: Maybe<any>; // jsonb
}

export type CreatePetition = PartialProps<
  Omit<Petition, "id">,
  | "name"
  | "custom_ref"
  | "is_template"
  | "status"
  | "deadline"
  | "email_subject"
  | "email_body"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "reminders_config"
  | "template_description"
  | "template_public"
  | "from_template_id"
  | "signature_config"
  | "hide_recipient_view_contents"
  | "skip_forward_security"
  | "public_metadata"
  | "from_public_petition_link_id"
  | "custom_properties"
  | "restricted_by_user_id"
  | "restricted_at"
  | "restricted_password_hash"
  | "restricted_password_salt"
  | "credits_used"
  | "closing_email_body"
  | "is_completing_message_enabled"
  | "completing_message_subject"
  | "completing_message_body"
  | "anonymized_at"
  | "metadata"
  | "closed_at"
  | "anonymize_after_months"
  | "anonymize_purpose"
  | "path"
  | "default_path"
  | "latest_signature_status"
  | "send_on_behalf_user_id"
  | "last_activity_at"
  | "last_recipient_activity_at"
  | "variables"
  | "enable_delegate_access"
  | "last_change_at"
  | "summary_config"
  | "summary_ai_completion_log_id"
  | "custom_lists"
  | "enable_interaction_with_recipients"
  | "enable_review_flow"
  | "enable_document_generation"
  | "automatic_numbering_config"
>;

export interface PetitionAccess {
  id: number; // int4
  petition_id: number; // int4
  granter_id: number; // int4
  contact_id: Maybe<number>; // int4
  keycode: string; // varchar
  status: PetitionAccessStatus; // petition_access_status
  next_reminder_at: Maybe<Date>; // timestamptz
  reminders_active: boolean; // bool
  reminders_config: Maybe<any>; // jsonb
  reminders_left: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  reminders_opt_out: boolean; // bool
  delegator_contact_id: Maybe<number>; // int4
  delegate_granter_id: Maybe<number>; // int4
  automatic_reminders_left: number; // int4
  is_shared_by_link: boolean; // bool
}

export type CreatePetitionAccess = PartialProps<
  Omit<PetitionAccess, "id">,
  | "contact_id"
  | "next_reminder_at"
  | "reminders_active"
  | "reminders_config"
  | "reminders_left"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "reminders_opt_out"
  | "delegator_contact_id"
  | "delegate_granter_id"
  | "automatic_reminders_left"
  | "is_shared_by_link"
>;

export interface PetitionAttachment {
  id: number; // int4
  petition_id: number; // int4
  file_upload_id: number; // int4
  type: PetitionAttachmentType; // petition_attachment_type
  position: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreatePetitionAttachment = PartialProps<
  Omit<PetitionAttachment, "id">,
  "created_at" | "created_by" | "updated_at" | "updated_by" | "deleted_at" | "deleted_by"
>;

export interface PetitionContactNotification {
  id: number; // int4
  petition_access_id: number; // int4
  petition_id: number; // int4
  type: PetitionContactNotificationType; // petition_contact_notification_type
  data: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  processed_at: Maybe<Date>; // timestamptz
  read_at: Maybe<Date>; // timestamptz
}

export type CreatePetitionContactNotification = PartialProps<
  Omit<PetitionContactNotification, "id">,
  "data" | "created_at" | "processed_at" | "read_at"
>;

export interface PetitionEvent {
  id: number; // int4
  petition_id: number; // int4
  type: PetitionEventType; // petition_event_type
  data: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  processed_at: Maybe<Date>; // timestamptz
  processed_by: Maybe<string>; // varchar
}

export type CreatePetitionEvent = PartialProps<
  Omit<PetitionEvent, "id">,
  "data" | "created_at" | "processed_at" | "processed_by"
>;

export interface PetitionField {
  id: number; // int4
  petition_id: number; // int4
  position: number; // int4
  type: PetitionFieldType; // petition_field_type
  title: Maybe<string>; // text
  description: Maybe<string>; // text
  optional: boolean; // bool
  multiple: boolean; // bool
  options: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  is_fixed: boolean; // bool
  visibility: Maybe<any>; // jsonb
  from_petition_field_id: Maybe<number>; // int4
  alias: Maybe<string>; // varchar
  is_internal: boolean; // bool
  show_in_pdf: boolean; // bool
  has_comments_enabled: boolean; // bool
  show_activity_in_pdf: boolean; // bool
  require_approval: boolean; // bool
  parent_petition_field_id: Maybe<number>; // int4
  math: Maybe<any>; // jsonb
  profile_type_id: Maybe<number>; // int4
  profile_type_field_id: Maybe<number>; // int4
}

export type CreatePetitionField = PartialProps<
  Omit<PetitionField, "id">,
  | "title"
  | "description"
  | "optional"
  | "multiple"
  | "options"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "is_fixed"
  | "visibility"
  | "from_petition_field_id"
  | "alias"
  | "is_internal"
  | "show_in_pdf"
  | "has_comments_enabled"
  | "show_activity_in_pdf"
  | "require_approval"
  | "parent_petition_field_id"
  | "math"
  | "profile_type_id"
  | "profile_type_field_id"
>;

export interface PetitionFieldAttachment {
  id: number; // int4
  petition_field_id: number; // int4
  file_upload_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreatePetitionFieldAttachment = PartialProps<
  Omit<PetitionFieldAttachment, "id">,
  "created_at" | "created_by" | "deleted_at" | "deleted_by"
>;

export interface PetitionFieldComment {
  id: number; // int4
  petition_id: number; // int4
  petition_field_id: Maybe<number>; // int4
  user_id: Maybe<number>; // int4
  petition_access_id: Maybe<number>; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  is_internal: boolean; // bool
  anonymized_at: Maybe<Date>; // timestamptz
  content_json: Maybe<any>; // jsonb
}

export type CreatePetitionFieldComment = PartialProps<
  Omit<PetitionFieldComment, "id">,
  | "petition_field_id"
  | "user_id"
  | "petition_access_id"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "is_internal"
  | "anonymized_at"
  | "content_json"
>;

export interface PetitionFieldGroupRelationship {
  id: number; // int4
  petition_id: number; // int4
  left_side_petition_field_id: number; // int4
  profile_relationship_type_id: number; // int4
  direction: ProfileRelationshipTypeDirection; // profile_relationship_type_direction
  right_side_petition_field_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreatePetitionFieldGroupRelationship = PartialProps<
  Omit<PetitionFieldGroupRelationship, "id">,
  "created_at" | "created_by" | "updated_at" | "updated_by" | "deleted_at" | "deleted_by"
>;

export interface PetitionFieldReply {
  id: number; // int4
  petition_field_id: number; // int4
  type: PetitionFieldType; // petition_field_type
  content: any; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  petition_access_id: Maybe<number>; // int4
  status: PetitionFieldReplyStatus; // petition_field_reply_status
  metadata: any; // jsonb
  user_id: Maybe<number>; // int4
  anonymized_at: Maybe<Date>; // timestamptz
  parent_petition_field_reply_id: Maybe<number>; // int4
  associated_profile_id: Maybe<number>; // int4
}

export type CreatePetitionFieldReply = PartialProps<
  Omit<PetitionFieldReply, "id">,
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "petition_access_id"
  | "status"
  | "metadata"
  | "user_id"
  | "anonymized_at"
  | "parent_petition_field_reply_id"
  | "associated_profile_id"
>;

export interface PetitionListView {
  id: number; // int4
  user_id: number; // int4
  name: string; // varchar
  data: any; // jsonb
  position: number; // int4
  is_default: boolean; // bool
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreatePetitionListView = PartialProps<
  Omit<PetitionListView, "id">,
  | "is_default"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface PetitionMessage {
  id: number; // int4
  petition_id: number; // int4
  petition_access_id: number; // int4
  sender_id: number; // int4
  email_subject: Maybe<string>; // varchar
  email_body: Maybe<string>; // text
  status: PetitionMessageStatus; // petition_message_status
  scheduled_at: Maybe<Date>; // timestamptz
  email_log_id: Maybe<number>; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  anonymized_at: Maybe<Date>; // timestamptz
}

export type CreatePetitionMessage = PartialProps<
  Omit<PetitionMessage, "id">,
  | "email_subject"
  | "email_body"
  | "scheduled_at"
  | "email_log_id"
  | "created_at"
  | "created_by"
  | "anonymized_at"
>;

export interface PetitionPermission {
  id: number; // int4
  petition_id: number; // int4
  user_id: Maybe<number>; // int4
  type: PetitionPermissionType; // petition_permission_type
  is_subscribed: boolean; // bool
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  user_group_id: Maybe<number>; // int4
  from_user_group_id: Maybe<number>; // int4
}

export type CreatePetitionPermission = PartialProps<
  Omit<PetitionPermission, "id">,
  | "user_id"
  | "type"
  | "is_subscribed"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "user_group_id"
  | "from_user_group_id"
>;

export interface PetitionProfile {
  id: number; // int4
  petition_id: number; // int4
  profile_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
}

export type CreatePetitionProfile = PartialProps<
  Omit<PetitionProfile, "id">,
  "created_at" | "created_by"
>;

export interface PetitionReminder {
  id: number; // int4
  email_log_id: Maybe<number>; // int4
  type: PetitionReminderType; // petition_reminder_type
  status: PetitionReminderStatus; // petition_reminder_status
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  sender_id: Maybe<number>; // int4
  petition_access_id: number; // int4
  email_body: Maybe<string>; // text
  anonymized_at: Maybe<Date>; // timestamptz
}

export type CreatePetitionReminder = PartialProps<
  Omit<PetitionReminder, "id">,
  "email_log_id" | "created_at" | "created_by" | "sender_id" | "email_body" | "anonymized_at"
>;

export interface PetitionSignatureRequest {
  id: number; // int4
  petition_id: number; // int4
  external_id: Maybe<string>; // varchar
  signature_config: any; // jsonb
  status: PetitionSignatureStatus; // petition_signature_status
  cancel_reason: Maybe<PetitionSignatureCancelReason>; // petition_signature_cancel_reason
  cancel_data: Maybe<any>; // jsonb
  data: Maybe<any>; // jsonb
  event_logs: Maybe<any>; // jsonb
  file_upload_id: Maybe<number>; // int4
  created_at: Date; // timestamptz
  updated_at: Date; // timestamptz
  file_upload_audit_trail_id: Maybe<number>; // int4
  metadata: any; // jsonb
  signer_status: any; // jsonb
  anonymized_at: Maybe<Date>; // timestamptz
  temporary_file_document_id: Maybe<number>; // int4
  processed_at: Maybe<Date>; // timestamptz
  processed_by: Maybe<string>; // varchar
}

export type CreatePetitionSignatureRequest = PartialProps<
  Omit<PetitionSignatureRequest, "id">,
  | "external_id"
  | "status"
  | "cancel_reason"
  | "cancel_data"
  | "data"
  | "event_logs"
  | "file_upload_id"
  | "created_at"
  | "updated_at"
  | "file_upload_audit_trail_id"
  | "metadata"
  | "signer_status"
  | "anonymized_at"
  | "temporary_file_document_id"
  | "processed_at"
  | "processed_by"
>;

export interface PetitionTag {
  id: number; // int4
  petition_id: number; // int4
  tag_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
}

export type CreatePetitionTag = PartialProps<Omit<PetitionTag, "id">, "created_at" | "created_by">;

export interface PetitionUserNotification {
  id: number; // int4
  user_id: number; // int4
  petition_id: number; // int4
  type: PetitionUserNotificationType; // petition_user_notification_type
  data: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  processed_at: Maybe<Date>; // timestamptz
  read_at: Maybe<Date>; // timestamptz
}

export type CreatePetitionUserNotification = PartialProps<
  Omit<PetitionUserNotification, "id">,
  "data" | "created_at" | "processed_at" | "read_at"
>;

export interface Profile {
  id: number; // int4
  org_id: number; // int4
  profile_type_id: number; // int4
  /**
   * @deprecated
   */
  name: string; // varchar
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  status: ProfileStatus; // profile_status
  closed_at: Maybe<Date>; // timestamptz
  deletion_scheduled_at: Maybe<Date>; // timestamptz
  anonymized_at: Maybe<Date>; // timestamptz
  localizable_name: any; // jsonb
}

export type CreateProfile = PartialProps<
  Omit<Profile, "id">,
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "status"
  | "closed_at"
  | "deletion_scheduled_at"
  | "anonymized_at"
  | "localizable_name"
>;

export interface ProfileEvent {
  id: number; // int4
  org_id: number; // int4
  profile_id: number; // int4
  type: ProfileEventType; // profile_event_type
  data: any; // jsonb
  created_at: Date; // timestamptz
  processed_at: Maybe<Date>; // timestamptz
  processed_by: Maybe<string>; // varchar
}

export type CreateProfileEvent = PartialProps<
  Omit<ProfileEvent, "id">,
  "data" | "created_at" | "processed_at" | "processed_by"
>;

export interface ProfileExternalSourceEntity {
  id: number; // int4
  integration_id: number; // int4
  data: any; // jsonb
  standard_type: ProfileTypeStandardType; // profile_type_standard_type
  parsed_data: any; // jsonb
  created_by_user_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
}

export type CreateProfileExternalSourceEntity = PartialProps<
  Omit<ProfileExternalSourceEntity, "id">,
  "parsed_data" | "created_at" | "created_by"
>;

export interface ProfileFieldFile {
  id: number; // int4
  profile_id: number; // int4
  profile_type_field_id: number; // int4
  type: ProfileTypeFieldType; // profile_type_field_type
  file_upload_id: Maybe<number>; // int4
  expiry_date: Maybe<string>; // date
  created_at: Date; // timestamptz
  created_by_user_id: number; // int4
  removed_at: Maybe<Date>; // timestamptz
  removed_by_user_id: Maybe<number>; // int4
  anonymized_at: Maybe<Date>; // timestamptz
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateProfileFieldFile = PartialProps<
  Omit<ProfileFieldFile, "id">,
  | "file_upload_id"
  | "expiry_date"
  | "created_at"
  | "removed_at"
  | "removed_by_user_id"
  | "anonymized_at"
  | "deleted_at"
  | "deleted_by"
>;

export interface ProfileFieldValue {
  id: number; // int4
  profile_id: number; // int4
  profile_type_field_id: number; // int4
  type: ProfileTypeFieldType; // profile_type_field_type
  content: any; // jsonb
  expiry_date: Maybe<string>; // date
  created_by_user_id: Maybe<number>; // int4
  created_at: Date; // timestamptz
  removed_at: Maybe<Date>; // timestamptz
  removed_by_user_id: Maybe<number>; // int4
  anonymized_at: Maybe<Date>; // timestamptz
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  external_source_integration_id: Maybe<number>; // int4
}

export type CreateProfileFieldValue = PartialProps<
  Omit<ProfileFieldValue, "id">,
  | "content"
  | "expiry_date"
  | "created_by_user_id"
  | "created_at"
  | "removed_at"
  | "removed_by_user_id"
  | "anonymized_at"
  | "deleted_at"
  | "deleted_by"
  | "external_source_integration_id"
>;

export interface ProfileRelationship {
  id: number; // int4
  org_id: number; // int4
  left_side_profile_id: number; // int4
  profile_relationship_type_id: number; // int4
  right_side_profile_id: number; // int4
  created_by_user_id: number; // int4
  created_at: Date; // timestamptz
  removed_at: Maybe<Date>; // timestamptz
  removed_by_user_id: Maybe<number>; // int4
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateProfileRelationship = PartialProps<
  Omit<ProfileRelationship, "id">,
  "created_at" | "removed_at" | "removed_by_user_id" | "deleted_at" | "deleted_by"
>;

export interface ProfileRelationshipType {
  id: number; // int4
  org_id: number; // int4
  left_right_name: any; // jsonb
  right_left_name: Maybe<any>; // jsonb
  is_reciprocal: boolean; // bool
  alias: Maybe<string>; // varchar
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateProfileRelationshipType = PartialProps<
  Omit<ProfileRelationshipType, "id">,
  | "left_right_name"
  | "right_left_name"
  | "is_reciprocal"
  | "alias"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface ProfileRelationshipTypeAllowedProfileType {
  id: number; // int4
  org_id: number; // int4
  profile_relationship_type_id: number; // int4
  allowed_profile_type_id: number; // int4
  direction: ProfileRelationshipTypeDirection; // profile_relationship_type_direction
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateProfileRelationshipTypeAllowedProfileType = PartialProps<
  Omit<ProfileRelationshipTypeAllowedProfileType, "id">,
  "created_at" | "created_by" | "updated_at" | "updated_by" | "deleted_at" | "deleted_by"
>;

export interface ProfileSubscription {
  id: number; // int4
  profile_id: number; // int4
  user_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateProfileSubscription = PartialProps<
  Omit<ProfileSubscription, "id">,
  "created_at" | "created_by" | "deleted_at" | "deleted_by"
>;

export interface ProfileType {
  id: number; // int4
  org_id: number; // int4
  name: any; // jsonb
  profile_name_pattern: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  archived_by_user_id: Maybe<number>; // int4
  archived_at: Maybe<Date>; // timestamptz
  standard_type: Maybe<ProfileTypeStandardType>; // profile_type_standard_type
}

export type CreateProfileType = PartialProps<
  Omit<ProfileType, "id">,
  | "name"
  | "profile_name_pattern"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "archived_by_user_id"
  | "archived_at"
  | "standard_type"
>;

export interface ProfileTypeField {
  id: number; // int4
  profile_type_id: number; // int4
  position: number; // int4
  name: any; // jsonb
  type: ProfileTypeFieldType; // profile_type_field_type
  options: any; // jsonb
  alias: Maybe<string>; // varchar
  is_expirable: boolean; // bool
  permission: ProfileTypeFieldPermissionType; // profile_type_field_permission_type
  expiry_alert_ahead_time: Maybe<Duration>; // interval
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateProfileTypeField = PartialProps<
  Omit<ProfileTypeField, "id">,
  | "name"
  | "options"
  | "alias"
  | "is_expirable"
  | "permission"
  | "expiry_alert_ahead_time"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface ProfileTypeFieldPermission {
  id: number; // int4
  profile_type_field_id: number; // int4
  permission: ProfileTypeFieldPermissionType; // profile_type_field_permission_type
  user_id: Maybe<number>; // int4
  user_group_id: Maybe<number>; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateProfileTypeFieldPermission = PartialProps<
  Omit<ProfileTypeFieldPermission, "id">,
  | "user_id"
  | "user_group_id"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface PublicFileUpload {
  id: number; // int4
  path: string; // varchar
  filename: string; // varchar
  size: string; // int8
  content_type: string; // varchar
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreatePublicFileUpload = PartialProps<
  Omit<PublicFileUpload, "id">,
  "created_at" | "created_by" | "updated_at" | "updated_by" | "deleted_at" | "deleted_by"
>;

export interface PublicPetitionLink {
  id: number; // int4
  template_id: number; // int4
  title: string; // varchar
  description: string; // text
  slug: string; // varchar
  is_active: boolean; // bool
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  prefill_secret: Maybe<string>; // varchar
  allow_multiple_petitions: boolean; // bool
  petition_name_pattern: Maybe<string>; // varchar
}

export type CreatePublicPetitionLink = PartialProps<
  Omit<PublicPetitionLink, "id">,
  | "is_active"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "prefill_secret"
  | "allow_multiple_petitions"
  | "petition_name_pattern"
>;

export interface PublicPetitionLinkPrefillData {
  id: number; // int4
  template_id: number; // int4
  keycode: string; // varchar
  data: any; // jsonb
  path: string; // text
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreatePublicPetitionLinkPrefillData = PartialProps<
  Omit<PublicPetitionLinkPrefillData, "id">,
  "data" | "path" | "created_at" | "created_by" | "deleted_at" | "deleted_by"
>;

export interface SystemEvent {
  id: number; // int4
  type: SystemEventType; // system_event_type
  data: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  processed_at: Maybe<Date>; // timestamptz
  processed_by: Maybe<string>; // varchar
}

export type CreateSystemEvent = PartialProps<
  Omit<SystemEvent, "id">,
  "data" | "created_at" | "processed_at" | "processed_by"
>;

export interface Tag {
  id: number; // int4
  organization_id: number; // int4
  name: string; // varchar
  color: string; // varchar
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateTag = PartialProps<
  Omit<Tag, "id">,
  "created_at" | "created_by" | "updated_at" | "updated_by" | "deleted_at" | "deleted_by"
>;

export interface Task {
  id: number; // int4
  user_id: Maybe<number>; // int4
  name: TaskName; // task_name
  status: TaskStatus; // task_status
  progress: Maybe<number>; // int4
  input: any; // jsonb
  output: Maybe<any>; // jsonb
  error_data: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  petition_access_id: Maybe<number>; // int4
  started_at: Maybe<Date>; // timestamptz
  anonymized_at: Maybe<Date>; // timestamptz
  processed_at: Maybe<Date>; // timestamptz
  processed_by: Maybe<string>; // varchar
}

export type CreateTask = PartialProps<
  Omit<Task, "id">,
  | "user_id"
  | "status"
  | "progress"
  | "input"
  | "output"
  | "error_data"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "petition_access_id"
  | "started_at"
  | "anonymized_at"
  | "processed_at"
  | "processed_by"
>;

export interface TemplateDefaultPermission {
  id: number; // int4
  template_id: number; // int4
  type: PetitionPermissionType; // petition_permission_type
  user_id: Maybe<number>; // int4
  user_group_id: Maybe<number>; // int4
  is_subscribed: boolean; // bool
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateTemplateDefaultPermission = PartialProps<
  Omit<TemplateDefaultPermission, "id">,
  | "user_id"
  | "user_group_id"
  | "is_subscribed"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface TemporaryFile {
  id: number; // int4
  path: string; // varchar
  filename: string; // varchar
  size: string; // int8
  content_type: string; // varchar
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
}

export type CreateTemporaryFile = PartialProps<
  Omit<TemporaryFile, "id">,
  "created_at" | "created_by"
>;

export interface User {
  id: number; // int4
  org_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  last_active_at: Maybe<Date>; // timestamptz
  status: UserStatus; // user_status
  external_id: Maybe<string>; // varchar
  user_data_id: number; // int4
  is_org_owner: boolean; // bool
}

export type CreateUser = PartialProps<
  Omit<User, "id">,
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "last_active_at"
  | "status"
  | "external_id"
  | "is_org_owner"
>;

export interface UserAuthenticationToken {
  id: number; // int4
  user_id: number; // int4
  token_name: string; // varchar
  token_hash: string; // varchar
  last_used_at: Maybe<Date>; // timestamptz
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  token_hint: Maybe<string>; // varchar
}

export type CreateUserAuthenticationToken = PartialProps<
  Omit<UserAuthenticationToken, "id">,
  "last_used_at" | "created_at" | "created_by" | "deleted_at" | "deleted_by" | "token_hint"
>;

export interface UserData {
  id: number; // int4
  cognito_id: string; // varchar
  email: string; // varchar
  first_name: Maybe<string>; // varchar
  last_name: Maybe<string>; // varchar
  is_sso_user: boolean; // bool
  avatar_public_file_id: Maybe<number>; // int4
  details: Maybe<any>; // jsonb
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  preferred_locale: UserLocale; // user_locale
}

export type CreateUserData = PartialProps<
  Omit<UserData, "id">,
  | "first_name"
  | "last_name"
  | "is_sso_user"
  | "avatar_public_file_id"
  | "details"
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
>;

export interface UserDelegate {
  id: number; // int4
  user_id: number; // int4
  delegate_user_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateUserDelegate = PartialProps<
  Omit<UserDelegate, "id">,
  "created_at" | "created_by" | "deleted_at" | "deleted_by"
>;

export interface UserGroup {
  id: number; // int4
  org_id: number; // int4
  name: string; // varchar
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
  type: UserGroupType; // user_group_type
  localizable_name: any; // jsonb
}

export type CreateUserGroup = PartialProps<
  Omit<UserGroup, "id">,
  | "created_at"
  | "created_by"
  | "updated_at"
  | "updated_by"
  | "deleted_at"
  | "deleted_by"
  | "type"
  | "localizable_name"
>;

export interface UserGroupMember {
  id: number; // int4
  user_group_id: number; // int4
  user_id: number; // int4
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateUserGroupMember = PartialProps<
  Omit<UserGroupMember, "id">,
  "created_at" | "created_by" | "deleted_at" | "deleted_by"
>;

export interface UserGroupPermission {
  id: number; // int4
  user_group_id: number; // int4
  name: UserGroupPermissionName; // user_group_permission_name
  effect: UserGroupPermissionEffect; // user_group_permission_effect
  created_at: Date; // timestamptz
  created_by: Maybe<string>; // varchar
  updated_at: Date; // timestamptz
  updated_by: Maybe<string>; // varchar
  deleted_at: Maybe<Date>; // timestamptz
  deleted_by: Maybe<string>; // varchar
}

export type CreateUserGroupPermission = PartialProps<
  Omit<UserGroupPermission, "id">,
  "created_at" | "created_by" | "updated_at" | "updated_by" | "deleted_at" | "deleted_by"
>;

export interface UserPetitionEventLog {
  id: string; // int8
  user_id: Maybe<number>; // int4
  petition_event_id: Maybe<number>; // int4
}

export type CreateUserPetitionEventLog = PartialProps<
  Omit<UserPetitionEventLog, "id">,
  "user_id" | "petition_event_id"
>;

export interface UserProfileEventLog {
  id: string; // int8
  user_id: Maybe<number>; // int4
  profile_event_id: Maybe<number>; // int4
}

export type CreateUserProfileEventLog = PartialProps<
  Omit<UserProfileEventLog, "id">,
  "user_id" | "profile_event_id"
>;
