/**
 * This file was automatically generated by generate-db-types
 * Do not make changes to this file directly
 */

export type Maybe<T> = T | null;

export type OrganizationStatus = "DEV" | "DEMO" | "ACTIVE" | "CHURNED";

export type PetitionFieldType = "FILE_UPLOAD" | "TEXT";

export type PetitionStatus = "DRAFT" | "PENDING" | "COMPLETED";

export type UserOrganizationRole = "NORMAL" | "ADMIN";

export interface TableTypes {
  contact: Contact;
  file_upload: FileUpload;
  organization: Organization;
  petition: Petition;
  petition_event_log: PetitionEventLog;
  petition_field: PetitionField;
  petition_field_reply: PetitionFieldReply;
  petition_sendout: PetitionSendout;
  user: User;
}

export interface TableCreateTypes {
  contact: CreateContact;
  file_upload: CreateFileUpload;
  organization: CreateOrganization;
  petition: CreatePetition;
  petition_event_log: CreatePetitionEventLog;
  petition_field: CreatePetitionField;
  petition_field_reply: CreatePetitionFieldReply;
  petition_sendout: CreatePetitionSendout;
  user: CreateUser;
}

export interface TablePrimaryKeys {
  contact: "id";
  file_upload: "id";
  organization: "id";
  petition: "id";
  petition_event_log: "id";
  petition_field: "id";
  petition_field_reply: "id";
  petition_sendout: "id";
  user: "id";
}

export interface Contact {
  id: number;
  email: string;
  first_name: Maybe<string>;
  last_name: Maybe<string>;
  org_id: number;
  owner_id: number;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreateContact {
  email: string;
  first_name?: Maybe<string>;
  last_name?: Maybe<string>;
  org_id: number;
  owner_id: number;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}

export interface FileUpload {
  id: number;
  path: string;
  filename: string;
  size: number;
  content_type: string;
  upload_complete: boolean;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreateFileUpload {
  path: string;
  filename: string;
  size: number;
  content_type: string;
  upload_complete?: boolean;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}

export interface Organization {
  id: number;
  name: string;
  identifier: string;
  status: OrganizationStatus;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreateOrganization {
  name: string;
  identifier: string;
  status: OrganizationStatus;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}

export interface Petition {
  id: number;
  org_id: number;
  owner_id: number;
  name: Maybe<string>;
  custom_ref: Maybe<string>;
  locale: string;
  is_template: boolean;
  status: Maybe<PetitionStatus>;
  deadline: Maybe<Date>;
  email_subject: Maybe<string>;
  email_body: Maybe<string>;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreatePetition {
  org_id: number;
  owner_id: number;
  name?: Maybe<string>;
  custom_ref?: Maybe<string>;
  locale: string;
  is_template?: boolean;
  status?: Maybe<PetitionStatus>;
  deadline?: Maybe<Date>;
  email_subject?: Maybe<string>;
  email_body?: Maybe<string>;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}

export interface PetitionEventLog {
  id: number;
  petition_id: number;
  petition_sendout_id: number;
  event: Maybe<string>;
  event_data: Maybe<any>;
  event_date: Date;
}

export interface CreatePetitionEventLog {
  petition_id: number;
  petition_sendout_id: number;
  event?: Maybe<string>;
  event_data?: Maybe<any>;
  event_date?: Date;
}

export interface PetitionField {
  id: number;
  petition_id: number;
  position: number;
  type: PetitionFieldType;
  title: Maybe<string>;
  description: Maybe<string>;
  optional: boolean;
  multiple: boolean;
  options: Maybe<any>;
  validated: boolean;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreatePetitionField {
  petition_id: number;
  position: number;
  type: PetitionFieldType;
  title?: Maybe<string>;
  description?: Maybe<string>;
  optional?: boolean;
  multiple?: boolean;
  options?: Maybe<any>;
  validated?: boolean;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}

export interface PetitionFieldReply {
  id: number;
  petition_field_id: number;
  petition_sendout_id: number;
  type: PetitionFieldType;
  content: any;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreatePetitionFieldReply {
  petition_field_id: number;
  petition_sendout_id: number;
  type: PetitionFieldType;
  content: any;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}

export interface PetitionSendout {
  id: number;
  petition_id: number;
  contact_id: number;
  sender_id: number;
  keycode: string;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreatePetitionSendout {
  petition_id: number;
  contact_id: number;
  sender_id: number;
  keycode: string;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}

export interface User {
  id: number;
  cognito_id: string;
  org_id: number;
  organization_role: UserOrganizationRole;
  email: string;
  first_name: Maybe<string>;
  last_name: Maybe<string>;
  created_at: Date;
  created_by: Maybe<string>;
  updated_at: Date;
  updated_by: Maybe<string>;
  deleted_at: Maybe<Date>;
  deleted_by: Maybe<string>;
}

export interface CreateUser {
  cognito_id: string;
  org_id: number;
  organization_role?: UserOrganizationRole;
  email: string;
  first_name?: Maybe<string>;
  last_name?: Maybe<string>;
  created_at?: Date;
  created_by?: Maybe<string>;
  updated_at?: Date;
  updated_by?: Maybe<string>;
  deleted_at?: Maybe<Date>;
  deleted_by?: Maybe<string>;
}
