import { ContainerModule } from "inversify";
import { BackgroundCheckProfilePdfRunner } from "./BackgroundCheckProfilePdfRunner";
import { BackgroundCheckResultsPdfRunner } from "./BackgroundCheckResultsPdfRunner";
import { BankflipSessionCompletedRunner } from "./BankflipSessionCompletedRunner";
import { BulkPetitionSendRunner } from "./BulkPetitionSendRunner";
import { ClosePetitionsRunner } from "./ClosePetitionsRunner";
import { DashboardRefreshRunner } from "./DashboardRefreshRunner";
import { DocumentProcessingRunner } from "./DocumentProcessingRunner";
import { DowJonesProfileDownloadRunner } from "./DowJonesProfileDownloadRunner";
import { ExportExcelRunner } from "./ExportExcelRunner";
import { ExportRepliesRunner } from "./ExportRepliesRunner";
import { FileExportRunner } from "./FileExportRunner";
import { IdVerificationSessionCompletedRunner } from "./IdVerificationSessionCompletedRunner";
import { PetitionSharingRunner } from "./PetitionSharingRunner";
import { PetitionSummaryRunner } from "./PetitionSummaryRunner";
import { PrintPdfRunner } from "./PrintPdfRunner";
import { ProfileNamePatternUpdatedRunner } from "./ProfileNamePatternUpdatedRunner";
import { ProfilesExcelExportRunner } from "./ProfilesExcelExportRunner";
import { ProfilesExcelImportRunner } from "./ProfilesExcelImportRunner";
import { TemplateRepliesCsvExportRunner } from "./TemplateRepliesCsvExportRunner";
import { TemplateRepliesReportRunner } from "./TemplateRepliesReportRunner";
import { TemplateStatsReportRunner } from "./TemplateStatsReportRunner";
import { TemplatesOverviewReportRunner } from "./TemplatesOverviewReportRunner";

export const taskRunnersModule = new ContainerModule((options) => {
  options.bind(PrintPdfRunner).toSelf();
  options.bind(ExportRepliesRunner).toSelf();
  options.bind(ExportExcelRunner).toSelf();
  options.bind(TemplateRepliesReportRunner).toSelf();
  options.bind(TemplateStatsReportRunner).toSelf();
  options.bind(DowJonesProfileDownloadRunner).toSelf();
  options.bind(TemplatesOverviewReportRunner).toSelf();
  options.bind(BankflipSessionCompletedRunner).toSelf();
  options.bind(BulkPetitionSendRunner).toSelf();
  options.bind(TemplateRepliesCsvExportRunner).toSelf();
  options.bind(PetitionSummaryRunner).toSelf();
  options.bind(BackgroundCheckProfilePdfRunner).toSelf();
  options.bind(BackgroundCheckResultsPdfRunner).toSelf();
  options.bind(PetitionSharingRunner).toSelf();
  options.bind(ProfileNamePatternUpdatedRunner).toSelf();
  options.bind(IdVerificationSessionCompletedRunner).toSelf();
  options.bind(FileExportRunner).toSelf();
  options.bind(ClosePetitionsRunner).toSelf();
  options.bind(ProfilesExcelImportRunner).toSelf();
  options.bind(ProfilesExcelExportRunner).toSelf();
  options.bind(DashboardRefreshRunner).toSelf();
  options.bind(DocumentProcessingRunner).toSelf();
});
