/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as ctx from "../context";
import * as db from "../db/__types";
import * as events from "./backing/events";
import { GlobalIdConfigSpread } from "./helpers/globalIdPlugin";
import { FieldAuthorizeResolver } from "@nexus/schema/dist/plugins/fieldAuthorizePlugin";
import { FieldValidateArgsResolver } from "./helpers/validateArgsPlugin";
import { core } from "@nexus/schema";
import { PaginationFieldConfig } from "./helpers/paginationPlugin";
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    datetime<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<"inputTypes", TypeName, FieldName>
      >
    ): void; // "DateTime";
    jsonObject<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<"inputTypes", TypeName, FieldName>
      >
    ): void; // "JSONObject";
    json<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<"inputTypes", TypeName, FieldName>
      >
    ): void; // "JSON";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    datetime<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "DateTime";
    jsonObject<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "JSONObject";
    json<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "JSON";
    globalId<FieldName extends string>(
      fieldName: FieldName,
      ...opts: GlobalIdConfigSpread<TypeName, FieldName>
    ): void;

    paginationField<
      FieldName extends string,
      PaginationType extends
        | core.GetGen<"allOutputTypes", string>
        | core.AllNexusOutputTypeDefs
    >(
      fieldName: FieldName,
      config: PaginationFieldConfig<TypeName, FieldName, PaginationType>
    ): void;
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateContactInput: {
    // input type
    email: string; // String!
    firstName?: string | null; // String
    lastName?: string | null; // String
  };
  CreateFileUploadReplyInput: {
    // input type
    contentType: string; // String!
    filename: string; // String!
    size: number; // Int!
  };
  CreateTextReplyInput: {
    // input type
    text: string; // String!
  };
  RemindersConfigInput: {
    // input type
    offset: number; // Int!
    time: string; // String!
    timezone: string; // String!
    weekdaysOnly: boolean; // Boolean!
  };
  UpdateContactInput: {
    // input type
    firstName?: string | null; // String
    lastName?: string | null; // String
  };
  UpdatePetitionFieldInput: {
    // input type
    description?: string | null; // String
    multiple?: boolean | null; // Boolean
    optional?: boolean | null; // Boolean
    options?: NexusGenScalars["JSONObject"] | null; // JSONObject
    title?: string | null; // String
  };
  UpdatePetitionInput: {
    // input type
    deadline?: NexusGenScalars["DateTime"] | null; // DateTime
    description?: string | null; // String
    emailBody?: NexusGenScalars["JSON"] | null; // JSON
    emailSubject?: string | null; // String
    locale?: NexusGenEnums["PetitionLocale"] | null; // PetitionLocale
    name?: string | null; // String
    remindersConfig?: NexusGenInputs["RemindersConfigInput"] | null; // RemindersConfigInput
  };
  UpdateUserInput: {
    // input type
    firstName?: string | null; // String
    lastName?: string | null; // String
  };
}

export interface NexusGenEnums {
  ChangePasswordResult:
    | "INCORRECT_PASSWORD"
    | "INVALID_NEW_PASSWORD"
    | "SUCCESS";
  OnboardingKey:
    | "CONTACT_DETAILS"
    | "CONTACT_LIST"
    | "PETITION_ACTIVITY"
    | "PETITION_COMPOSE"
    | "PETITION_REVIEW"
    | "PETITIONS_LIST";
  OnboardingStatus: "FINISHED" | "SKIPPED";
  OrganizationRole: "ADMIN" | "NORMAL";
  OrganizationStatus: db.OrganizationStatus;
  PetitionAccessStatus: db.PetitionAccessStatus;
  PetitionBaseType: "PETITION" | "TEMPLATE";
  PetitionFieldReplyStatus: db.PetitionFieldReplyStatus;
  PetitionFieldType: db.PetitionFieldType;
  PetitionLocale: "en" | "es";
  PetitionMessageStatus: db.PetitionMessageStatus;
  PetitionReminderType: db.PetitionReminderType;
  PetitionStatus: db.PetitionStatus;
  PetitionUserPermissionType: db.PetitionUserPermissionType;
  PetitionUserPermissionTypeRW: "READ" | "WRITE";
  QueryContacts_OrderBy:
    | "createdAt_ASC"
    | "createdAt_DESC"
    | "email_ASC"
    | "email_DESC"
    | "firstName_ASC"
    | "firstName_DESC"
    | "fullName_ASC"
    | "fullName_DESC"
    | "lastName_ASC"
    | "lastName_DESC";
  QueryPetitions_OrderBy:
    | "createdAt_ASC"
    | "createdAt_DESC"
    | "name_ASC"
    | "name_DESC";
  Result: "FAILURE" | "SUCCESS";
}

export interface NexusGenScalars {
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: Date;
  GID: number;
  JSON: any;
  JSONObject: { [key: string]: any };
}

export interface NexusGenRootTypes {
  AccessActivatedEvent: events.AccessActivatedEvent;
  AccessDeactivatedEvent: events.AccessDeactivatedEvent;
  AccessOpenedEvent: events.AccessOpenedEvent;
  CommentDeletedEvent: events.CommentDeletedEvent;
  CommentPublishedEvent: events.CommentPublishedEvent;
  Contact: db.Contact;
  ContactPagination: {
    // root type
    items: NexusGenRootTypes["Contact"][]; // [Contact!]!
    totalCount: number; // Int!
  };
  CreateFileUploadReply: {
    // root type
    endpoint: string; // String!
    reply: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
  };
  FileUploadReplyDownloadLinkResult: {
    // root type
    result: NexusGenEnums["Result"]; // Result!
    url?: string | null; // String
  };
  MessageCancelledEvent: events.MessageCancelledEvent;
  MessageScheduledEvent: events.MessageScheduledEvent;
  MessageSentEvent: events.MessageSentEvent;
  Mutation: {};
  Organization: db.Organization;
  OwnershipTransferredEvent: events.OwnershipTransferredEvent;
  Petition: db.Petition;
  PetitionAccess: db.PetitionAccess;
  PetitionAccessPagination: {
    // root type
    items: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    totalCount: number; // Int!
  };
  PetitionAndField: {
    // root type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    petition: NexusGenRootTypes["Petition"]; // Petition!
  };
  PetitionBasePagination: {
    // root type
    items: NexusGenRootTypes["PetitionBase"][]; // [PetitionBase!]!
    totalCount: number; // Int!
  };
  PetitionCompletedEvent: events.PetitionCompletedEvent;
  PetitionCreatedEvent: events.PetitionCreatedEvent;
  PetitionEventPagination: {
    // root type
    items: NexusGenRootTypes["PetitionEvent"][]; // [PetitionEvent!]!
    totalCount: number; // Int!
  };
  PetitionField: db.PetitionField;
  PetitionFieldAndReplies: {
    // root type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    replies: NexusGenRootTypes["PetitionFieldReply"][]; // [PetitionFieldReply!]!
  };
  PetitionFieldComment: db.PetitionFieldComment;
  PetitionFieldReply: db.PetitionFieldReply;
  PetitionMessage: db.PetitionMessage;
  PetitionProgress: {
    // root type
    optional: number; // Int!
    replied: number; // Int!
    total: number; // Int!
    validated: number; // Int!
  };
  PetitionReminder: db.PetitionReminder;
  PetitionTemplate: db.Petition;
  PetitionTemplateAndField: {
    // root type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    petition: NexusGenRootTypes["PetitionTemplate"]; // PetitionTemplate!
  };
  PetitionTemplatePagination: {
    // root type
    items: NexusGenRootTypes["PetitionTemplate"][]; // [PetitionTemplate!]!
    totalCount: number; // Int!
  };
  PetitionUserPermission: db.PetitionUser;
  PublicContact: db.Contact;
  PublicOrganization: db.Organization;
  PublicPetition: db.Petition;
  PublicPetitionAccess: db.PetitionAccess;
  PublicPetitionField: db.PetitionField;
  PublicPetitionFieldComment: db.PetitionFieldComment;
  PublicPetitionFieldReply: db.PetitionFieldReply;
  PublicUser: db.User;
  Query: {};
  ReminderSentEvent: events.ReminderSentEvent;
  RemindersConfig: {
    // root type
    offset: number; // Int!
    time: string; // String!
    timezone: string; // String!
    weekdaysOnly: boolean; // Boolean!
  };
  ReplyCreatedEvent: events.ReplyCreatedEvent;
  ReplyDeletedEvent: events.ReplyDeletedEvent;
  SendPetitionResult: {
    // root type
    accesses?: NexusGenRootTypes["PetitionAccess"][] | null; // [PetitionAccess!]
    petition?: NexusGenRootTypes["Petition"] | null; // Petition
    result: NexusGenEnums["Result"]; // Result!
  };
  User: db.User;
  UserPagination: {
    // root type
    items: NexusGenRootTypes["User"][]; // [User!]!
    totalCount: number; // Int!
  };
  UserPermissionAddedEvent: events.UserPermissionAddedEvent;
  UserPermissionEditedEvent: events.UserPermissionEditedEvent;
  UserPermissionRemovedEvent: events.UserPermissionRemovedEvent;
  CreatedAt: {
    created_at: Date;
  };
  PetitionBase: db.Petition;
  PetitionBaseAndField: {
    petition: db.Petition;
    field: db.PetitionField;
  };
  PetitionEvent: events.PetitionEvent;
  Timestamps: {
    created_at: Date;
    updated_at: Date;
  };
  PublicUserOrContact:
    | ({ __type: "Contact" } & NexusGenRootTypes["Contact"])
    | ({ __type: "User" } & NexusGenRootTypes["User"]);
  UserOrPetitionAccess:
    | ({ __type: "User" } & NexusGenRootTypes["User"])
    | ({ __type: "PetitionAccess" } & NexusGenRootTypes["PetitionAccess"]);
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  CreateContactInput: NexusGenInputs["CreateContactInput"];
  CreateFileUploadReplyInput: NexusGenInputs["CreateFileUploadReplyInput"];
  CreateTextReplyInput: NexusGenInputs["CreateTextReplyInput"];
  RemindersConfigInput: NexusGenInputs["RemindersConfigInput"];
  UpdateContactInput: NexusGenInputs["UpdateContactInput"];
  UpdatePetitionFieldInput: NexusGenInputs["UpdatePetitionFieldInput"];
  UpdatePetitionInput: NexusGenInputs["UpdatePetitionInput"];
  UpdateUserInput: NexusGenInputs["UpdateUserInput"];
  ChangePasswordResult: NexusGenEnums["ChangePasswordResult"];
  OnboardingKey: NexusGenEnums["OnboardingKey"];
  OnboardingStatus: NexusGenEnums["OnboardingStatus"];
  OrganizationRole: NexusGenEnums["OrganizationRole"];
  OrganizationStatus: NexusGenEnums["OrganizationStatus"];
  PetitionAccessStatus: NexusGenEnums["PetitionAccessStatus"];
  PetitionBaseType: NexusGenEnums["PetitionBaseType"];
  PetitionFieldReplyStatus: NexusGenEnums["PetitionFieldReplyStatus"];
  PetitionFieldType: NexusGenEnums["PetitionFieldType"];
  PetitionLocale: NexusGenEnums["PetitionLocale"];
  PetitionMessageStatus: NexusGenEnums["PetitionMessageStatus"];
  PetitionReminderType: NexusGenEnums["PetitionReminderType"];
  PetitionStatus: NexusGenEnums["PetitionStatus"];
  PetitionUserPermissionType: NexusGenEnums["PetitionUserPermissionType"];
  PetitionUserPermissionTypeRW: NexusGenEnums["PetitionUserPermissionTypeRW"];
  QueryContacts_OrderBy: NexusGenEnums["QueryContacts_OrderBy"];
  QueryPetitions_OrderBy: NexusGenEnums["QueryPetitions_OrderBy"];
  Result: NexusGenEnums["Result"];
  String: NexusGenScalars["String"];
  Int: NexusGenScalars["Int"];
  Float: NexusGenScalars["Float"];
  Boolean: NexusGenScalars["Boolean"];
  ID: NexusGenScalars["ID"];
  DateTime: NexusGenScalars["DateTime"];
  GID: NexusGenScalars["GID"];
  JSON: NexusGenScalars["JSON"];
  JSONObject: NexusGenScalars["JSONObject"];
}

export interface NexusGenFieldTypes {
  AccessActivatedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    user: NexusGenRootTypes["User"] | null; // User
  };
  AccessDeactivatedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    user: NexusGenRootTypes["User"] | null; // User
  };
  AccessOpenedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
  };
  CommentDeletedEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    deletedBy: NexusGenRootTypes["UserOrPetitionAccess"] | null; // UserOrPetitionAccess
    field: NexusGenRootTypes["PetitionField"] | null; // PetitionField
    id: NexusGenScalars["GID"]; // GID!
  };
  CommentPublishedEvent: {
    // field return type
    comment: NexusGenRootTypes["PetitionFieldComment"] | null; // PetitionFieldComment
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    field: NexusGenRootTypes["PetitionField"] | null; // PetitionField
    id: NexusGenScalars["GID"]; // GID!
  };
  Contact: {
    // field return type
    accesses: NexusGenRootTypes["PetitionAccessPagination"]; // PetitionAccessPagination!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    email: string; // String!
    firstName: string | null; // String
    fullName: string | null; // String
    id: NexusGenScalars["GID"]; // GID!
    lastName: string | null; // String
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
  };
  ContactPagination: {
    // field return type
    items: NexusGenRootTypes["Contact"][]; // [Contact!]!
    totalCount: number; // Int!
  };
  CreateFileUploadReply: {
    // field return type
    endpoint: string; // String!
    reply: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
  };
  FileUploadReplyDownloadLinkResult: {
    // field return type
    result: NexusGenEnums["Result"]; // Result!
    url: string | null; // String
  };
  MessageCancelledEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    message: NexusGenRootTypes["PetitionMessage"]; // PetitionMessage!
    user: NexusGenRootTypes["User"] | null; // User
  };
  MessageScheduledEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    message: NexusGenRootTypes["PetitionMessage"]; // PetitionMessage!
  };
  MessageSentEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    message: NexusGenRootTypes["PetitionMessage"]; // PetitionMessage!
  };
  Mutation: {
    // field return type
    addPetitionUserPermission: NexusGenRootTypes["Petition"][]; // [Petition!]!
    cancelScheduledMessage: NexusGenRootTypes["PetitionMessage"] | null; // PetitionMessage
    changePassword: NexusGenEnums["ChangePasswordResult"]; // ChangePasswordResult!
    changePetitionFieldType: NexusGenRootTypes["PetitionBaseAndField"]; // PetitionBaseAndField!
    clonePetitionField: NexusGenRootTypes["PetitionBaseAndField"]; // PetitionBaseAndField!
    clonePetitions: NexusGenRootTypes["PetitionBase"][]; // [PetitionBase!]!
    createContact: NexusGenRootTypes["Contact"]; // Contact!
    createPetition: NexusGenRootTypes["PetitionBase"]; // PetitionBase!
    createPetitionField: NexusGenRootTypes["PetitionBaseAndField"]; // PetitionBaseAndField!
    createPetitionFieldComment: NexusGenRootTypes["PetitionFieldComment"]; // PetitionFieldComment!
    deactivateAccesses: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    deleteContacts: NexusGenEnums["Result"]; // Result!
    deletePetitionField: NexusGenRootTypes["PetitionBase"]; // PetitionBase!
    deletePetitionFieldComment: NexusGenEnums["Result"]; // Result!
    deletePetitions: NexusGenEnums["Result"]; // Result!
    editPetitionUserPermission: NexusGenRootTypes["Petition"][]; // [Petition!]!
    fileUploadReplyDownloadLink: NexusGenRootTypes["FileUploadReplyDownloadLinkResult"]; // FileUploadReplyDownloadLinkResult!
    markPetitionFieldCommentsAsRead: NexusGenRootTypes["PetitionFieldComment"][]; // [PetitionFieldComment!]!
    publicCompletePetition: NexusGenRootTypes["PublicPetition"]; // PublicPetition!
    publicCreateFileUploadReply: NexusGenRootTypes["CreateFileUploadReply"]; // CreateFileUploadReply!
    publicCreatePetitionFieldComment: NexusGenRootTypes["PublicPetitionFieldComment"]; // PublicPetitionFieldComment!
    publicCreateTextReply: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
    publicDeletePetitionFieldComment: NexusGenEnums["Result"]; // Result!
    publicDeletePetitionReply: NexusGenEnums["Result"]; // Result!
    publicFileUploadReplyComplete: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
    publicMarkPetitionFieldCommentsAsRead: NexusGenRootTypes["PublicPetitionFieldComment"][]; // [PublicPetitionFieldComment!]!
    publicSubmitUnpublishedComments: NexusGenRootTypes["PublicPetitionFieldComment"][]; // [PublicPetitionFieldComment!]!
    publicUpdatePetitionFieldComment: NexusGenRootTypes["PublicPetitionFieldComment"]; // PublicPetitionFieldComment!
    reactivateAccesses: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    removePetitionUserPermission: NexusGenRootTypes["Petition"][]; // [Petition!]!
    sendMessages: NexusGenEnums["Result"]; // Result!
    sendPetition: NexusGenRootTypes["SendPetitionResult"]; // SendPetitionResult!
    sendReminders: NexusGenEnums["Result"]; // Result!
    submitUnpublishedComments: NexusGenRootTypes["PetitionFieldComment"][]; // [PetitionFieldComment!]!
    switchAutomaticReminders: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    transferPetitionOwnership: NexusGenRootTypes["Petition"][]; // [Petition!]!
    updateContact: NexusGenRootTypes["Contact"]; // Contact!
    updateFieldPositions: NexusGenRootTypes["PetitionBase"]; // PetitionBase!
    updateOnboardingStatus: NexusGenRootTypes["User"]; // User!
    updatePetition: NexusGenRootTypes["PetitionBase"]; // PetitionBase!
    updatePetitionField: NexusGenRootTypes["PetitionBaseAndField"]; // PetitionBaseAndField!
    updatePetitionFieldComment: NexusGenRootTypes["PetitionFieldComment"]; // PetitionFieldComment!
    updatePetitionFieldRepliesStatus: NexusGenRootTypes["PetitionFieldAndReplies"]; // PetitionFieldAndReplies!
    updateUser: NexusGenRootTypes["User"]; // User!
    validatePetitionFields: NexusGenRootTypes["PetitionField"][]; // [PetitionField!]!
  };
  Organization: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    identifier: string; // String!
    name: string; // String!
    status: NexusGenEnums["OrganizationStatus"]; // OrganizationStatus!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
    users: NexusGenRootTypes["UserPagination"]; // UserPagination!
  };
  OwnershipTransferredEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    owner: NexusGenRootTypes["User"] | null; // User
    user: NexusGenRootTypes["User"] | null; // User
  };
  Petition: {
    // field return type
    accesses: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    deadline: NexusGenScalars["DateTime"] | null; // DateTime
    emailBody: NexusGenScalars["JSON"] | null; // JSON
    emailSubject: string | null; // String
    events: NexusGenRootTypes["PetitionEventPagination"]; // PetitionEventPagination!
    fieldCount: number; // Int!
    fields: NexusGenRootTypes["PetitionField"][]; // [PetitionField!]!
    id: NexusGenScalars["GID"]; // GID!
    locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
    name: string | null; // String
    owner: NexusGenRootTypes["User"]; // User!
    progress: NexusGenRootTypes["PetitionProgress"]; // PetitionProgress!
    remindersConfig: NexusGenRootTypes["RemindersConfig"] | null; // RemindersConfig
    status: NexusGenEnums["PetitionStatus"]; // PetitionStatus!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
    userPermissions: NexusGenRootTypes["PetitionUserPermission"][]; // [PetitionUserPermission!]!
  };
  PetitionAccess: {
    // field return type
    contact: NexusGenRootTypes["Contact"] | null; // Contact
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    granter: NexusGenRootTypes["User"] | null; // User
    id: NexusGenScalars["GID"]; // GID!
    nextReminderAt: NexusGenScalars["DateTime"] | null; // DateTime
    petition: NexusGenRootTypes["Petition"] | null; // Petition
    reminderCount: number; // Int!
    remindersActive: boolean; // Boolean!
    remindersConfig: NexusGenRootTypes["RemindersConfig"] | null; // RemindersConfig
    remindersLeft: number; // Int!
    status: NexusGenEnums["PetitionAccessStatus"]; // PetitionAccessStatus!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
  };
  PetitionAccessPagination: {
    // field return type
    items: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    totalCount: number; // Int!
  };
  PetitionAndField: {
    // field return type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    petition: NexusGenRootTypes["Petition"]; // Petition!
  };
  PetitionBasePagination: {
    // field return type
    items: NexusGenRootTypes["PetitionBase"][]; // [PetitionBase!]!
    totalCount: number; // Int!
  };
  PetitionCompletedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
  };
  PetitionCreatedEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    user: NexusGenRootTypes["User"] | null; // User
  };
  PetitionEventPagination: {
    // field return type
    items: NexusGenRootTypes["PetitionEvent"][]; // [PetitionEvent!]!
    totalCount: number; // Int!
  };
  PetitionField: {
    // field return type
    comments: NexusGenRootTypes["PetitionFieldComment"][]; // [PetitionFieldComment!]!
    description: string | null; // String
    id: NexusGenScalars["GID"]; // GID!
    isFixed: boolean; // Boolean!
    isReadOnly: boolean; // Boolean!
    multiple: boolean; // Boolean!
    optional: boolean; // Boolean!
    options: NexusGenScalars["JSONObject"] | null; // JSONObject
    position: number; // Int!
    replies: NexusGenRootTypes["PetitionFieldReply"][]; // [PetitionFieldReply!]!
    title: string | null; // String
    type: NexusGenEnums["PetitionFieldType"]; // PetitionFieldType!
    validated: boolean; // Boolean!
  };
  PetitionFieldAndReplies: {
    // field return type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    replies: NexusGenRootTypes["PetitionFieldReply"][]; // [PetitionFieldReply!]!
  };
  PetitionFieldComment: {
    // field return type
    author: NexusGenRootTypes["UserOrPetitionAccess"] | null; // UserOrPetitionAccess
    content: string; // String!
    id: NexusGenScalars["GID"]; // GID!
    isEdited: boolean; // Boolean!
    isUnread: boolean; // Boolean!
    publishedAt: NexusGenScalars["DateTime"] | null; // DateTime
    reply: NexusGenRootTypes["PetitionFieldReply"] | null; // PetitionFieldReply
  };
  PetitionFieldReply: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    content: NexusGenScalars["JSONObject"]; // JSONObject!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    field: NexusGenRootTypes["PetitionField"] | null; // PetitionField
    id: NexusGenScalars["GID"]; // GID!
    status: NexusGenEnums["PetitionFieldReplyStatus"]; // PetitionFieldReplyStatus!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
  };
  PetitionMessage: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    bouncedAt: NexusGenScalars["DateTime"] | null; // DateTime
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    deliveredAt: NexusGenScalars["DateTime"] | null; // DateTime
    emailBody: NexusGenScalars["JSON"] | null; // JSON
    emailSubject: NexusGenScalars["JSON"] | null; // JSON
    id: NexusGenScalars["GID"]; // GID!
    openedAt: NexusGenScalars["DateTime"] | null; // DateTime
    scheduledAt: NexusGenScalars["DateTime"] | null; // DateTime
    sender: NexusGenRootTypes["User"]; // User!
    sentAt: NexusGenScalars["DateTime"] | null; // DateTime
    status: NexusGenEnums["PetitionMessageStatus"]; // PetitionMessageStatus!
  };
  PetitionProgress: {
    // field return type
    optional: number; // Int!
    replied: number; // Int!
    total: number; // Int!
    validated: number; // Int!
  };
  PetitionReminder: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    sender: NexusGenRootTypes["User"] | null; // User
    type: NexusGenEnums["PetitionReminderType"]; // PetitionReminderType!
  };
  PetitionTemplate: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    description: string | null; // String
    emailBody: NexusGenScalars["JSON"] | null; // JSON
    emailSubject: string | null; // String
    fieldCount: number; // Int!
    fields: NexusGenRootTypes["PetitionField"][]; // [PetitionField!]!
    id: NexusGenScalars["GID"]; // GID!
    isPublic: boolean; // Boolean!
    locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
    name: string | null; // String
    owner: NexusGenRootTypes["User"]; // User!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
    userPermissions: NexusGenRootTypes["PetitionUserPermission"][]; // [PetitionUserPermission!]!
  };
  PetitionTemplateAndField: {
    // field return type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    petition: NexusGenRootTypes["PetitionTemplate"]; // PetitionTemplate!
  };
  PetitionTemplatePagination: {
    // field return type
    items: NexusGenRootTypes["PetitionTemplate"][]; // [PetitionTemplate!]!
    totalCount: number; // Int!
  };
  PetitionUserPermission: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    isSubscribed: boolean; // Boolean!
    permissionType: NexusGenEnums["PetitionUserPermissionType"]; // PetitionUserPermissionType!
    petition: NexusGenRootTypes["Petition"]; // Petition!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
    user: NexusGenRootTypes["User"]; // User!
  };
  PublicContact: {
    // field return type
    email: string; // String!
    firstName: string | null; // String
    fullName: string | null; // String
    id: NexusGenScalars["GID"]; // GID!
    lastName: string | null; // String
  };
  PublicOrganization: {
    // field return type
    id: NexusGenScalars["GID"]; // GID!
    identifier: string; // String!
    logoUrl: string | null; // String
    name: string; // String!
  };
  PublicPetition: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    deadline: NexusGenScalars["DateTime"] | null; // DateTime
    fields: NexusGenRootTypes["PublicPetitionField"][]; // [PublicPetitionField!]!
    id: NexusGenScalars["GID"]; // GID!
    locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
    status: NexusGenEnums["PetitionStatus"]; // PetitionStatus!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
  };
  PublicPetitionAccess: {
    // field return type
    contact: NexusGenRootTypes["PublicContact"] | null; // PublicContact
    granter: NexusGenRootTypes["PublicUser"] | null; // PublicUser
    petition: NexusGenRootTypes["PublicPetition"] | null; // PublicPetition
  };
  PublicPetitionField: {
    // field return type
    comments: NexusGenRootTypes["PublicPetitionFieldComment"][]; // [PublicPetitionFieldComment!]!
    description: string | null; // String
    id: NexusGenScalars["GID"]; // GID!
    isReadOnly: boolean; // Boolean!
    multiple: boolean; // Boolean!
    optional: boolean; // Boolean!
    options: NexusGenScalars["JSONObject"] | null; // JSONObject
    replies: NexusGenRootTypes["PublicPetitionFieldReply"][]; // [PublicPetitionFieldReply!]!
    title: string | null; // String
    type: NexusGenEnums["PetitionFieldType"]; // PetitionFieldType!
    validated: boolean; // Boolean!
  };
  PublicPetitionFieldComment: {
    // field return type
    author: NexusGenRootTypes["PublicUserOrContact"] | null; // PublicUserOrContact
    content: string; // String!
    id: NexusGenScalars["GID"]; // GID!
    isUnread: boolean; // Boolean!
    publishedAt: NexusGenScalars["DateTime"] | null; // DateTime
    reply: NexusGenRootTypes["PublicPetitionFieldReply"] | null; // PublicPetitionFieldReply
  };
  PublicPetitionFieldReply: {
    // field return type
    content: NexusGenScalars["JSONObject"]; // JSONObject!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    status: NexusGenEnums["PetitionFieldReplyStatus"]; // PetitionFieldReplyStatus!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
  };
  PublicUser: {
    // field return type
    email: string; // String!
    firstName: string | null; // String
    fullName: string | null; // String
    id: NexusGenScalars["GID"]; // GID!
    lastName: string | null; // String
    organization: NexusGenRootTypes["PublicOrganization"]; // PublicOrganization!
  };
  Query: {
    // field return type
    access: NexusGenRootTypes["PublicPetitionAccess"] | null; // PublicPetitionAccess
    contact: NexusGenRootTypes["Contact"] | null; // Contact
    contacts: NexusGenRootTypes["ContactPagination"]; // ContactPagination!
    me: NexusGenRootTypes["User"]; // User!
    organization: NexusGenRootTypes["Organization"] | null; // Organization
    petition: NexusGenRootTypes["PetitionBase"] | null; // PetitionBase
    petitions: NexusGenRootTypes["PetitionBasePagination"]; // PetitionBasePagination!
    publicTemplates: NexusGenRootTypes["PetitionTemplatePagination"]; // PetitionTemplatePagination!
  };
  ReminderSentEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    reminder: NexusGenRootTypes["PetitionReminder"]; // PetitionReminder!
  };
  RemindersConfig: {
    // field return type
    offset: number; // Int!
    time: string; // String!
    timezone: string; // String!
    weekdaysOnly: boolean; // Boolean!
  };
  ReplyCreatedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    field: NexusGenRootTypes["PetitionField"] | null; // PetitionField
    id: NexusGenScalars["GID"]; // GID!
    reply: NexusGenRootTypes["PetitionFieldReply"] | null; // PetitionFieldReply
  };
  ReplyDeletedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    field: NexusGenRootTypes["PetitionField"] | null; // PetitionField
    id: NexusGenScalars["GID"]; // GID!
  };
  SendPetitionResult: {
    // field return type
    accesses: NexusGenRootTypes["PetitionAccess"][] | null; // [PetitionAccess!]
    petition: NexusGenRootTypes["Petition"] | null; // Petition
    result: NexusGenEnums["Result"]; // Result!
  };
  User: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    email: string; // String!
    firstName: string | null; // String
    fullName: string | null; // String
    id: NexusGenScalars["GID"]; // GID!
    lastName: string | null; // String
    onboardingStatus: NexusGenScalars["JSONObject"]; // JSONObject!
    organization: NexusGenRootTypes["Organization"]; // Organization!
    organizationRole: NexusGenEnums["OrganizationRole"]; // OrganizationRole!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
  };
  UserPagination: {
    // field return type
    items: NexusGenRootTypes["User"][]; // [User!]!
    totalCount: number; // Int!
  };
  UserPermissionAddedEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    permissionType: NexusGenEnums["PetitionUserPermissionType"]; // PetitionUserPermissionType!
    permissionUser: NexusGenRootTypes["User"] | null; // User
    user: NexusGenRootTypes["User"] | null; // User
  };
  UserPermissionEditedEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    permissionType: NexusGenEnums["PetitionUserPermissionType"]; // PetitionUserPermissionType!
    permissionUser: NexusGenRootTypes["User"] | null; // User
    user: NexusGenRootTypes["User"] | null; // User
  };
  UserPermissionRemovedEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
    permissionUser: NexusGenRootTypes["User"] | null; // User
    user: NexusGenRootTypes["User"] | null; // User
  };
  CreatedAt: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
  };
  PetitionBase: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    emailBody: NexusGenScalars["JSON"] | null; // JSON
    emailSubject: string | null; // String
    fieldCount: number; // Int!
    fields: NexusGenRootTypes["PetitionField"][]; // [PetitionField!]!
    id: NexusGenScalars["GID"]; // GID!
    locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
    name: string | null; // String
    owner: NexusGenRootTypes["User"]; // User!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
    userPermissions: NexusGenRootTypes["PetitionUserPermission"][]; // [PetitionUserPermission!]!
  };
  PetitionBaseAndField: {
    // field return type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    petition: NexusGenRootTypes["PetitionBase"]; // PetitionBase!
  };
  PetitionEvent: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    id: NexusGenScalars["GID"]; // GID!
  };
  Timestamps: {
    // field return type
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    updatedAt: NexusGenScalars["DateTime"]; // DateTime!
  };
}

export interface NexusGenArgTypes {
  Contact: {
    accesses: {
      // args
      limit?: number | null; // Int
      offset?: number | null; // Int
    };
  };
  Mutation: {
    addPetitionUserPermission: {
      // args
      message?: string | null; // String
      notify?: boolean | null; // Boolean
      permissionType: NexusGenEnums["PetitionUserPermissionTypeRW"]; // PetitionUserPermissionTypeRW!
      petitionIds: NexusGenScalars["GID"][]; // [GID!]!
      userIds: NexusGenScalars["GID"][]; // [GID!]!
    };
    cancelScheduledMessage: {
      // args
      messageId: NexusGenScalars["GID"]; // GID!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    changePassword: {
      // args
      newPassword: string; // String!
      password: string; // String!
    };
    changePetitionFieldType: {
      // args
      fieldId: NexusGenScalars["GID"]; // GID!
      force?: boolean | null; // Boolean
      petitionId: NexusGenScalars["GID"]; // GID!
      type: NexusGenEnums["PetitionFieldType"]; // PetitionFieldType!
    };
    clonePetitionField: {
      // args
      fieldId: NexusGenScalars["GID"]; // GID!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    clonePetitions: {
      // args
      petitionIds: NexusGenScalars["GID"][]; // [GID!]!
    };
    createContact: {
      // args
      data: NexusGenInputs["CreateContactInput"]; // CreateContactInput!
    };
    createPetition: {
      // args
      locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
      name?: string | null; // String
      petitionId?: NexusGenScalars["GID"] | null; // GID
      type?: NexusGenEnums["PetitionBaseType"] | null; // PetitionBaseType
    };
    createPetitionField: {
      // args
      petitionId: NexusGenScalars["GID"]; // GID!
      position?: number | null; // Int
      type: NexusGenEnums["PetitionFieldType"]; // PetitionFieldType!
    };
    createPetitionFieldComment: {
      // args
      content: string; // String!
      petitionFieldId: NexusGenScalars["GID"]; // GID!
      petitionFieldReplyId?: NexusGenScalars["GID"] | null; // GID
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    deactivateAccesses: {
      // args
      accessIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    deleteContacts: {
      // args
      ids: NexusGenScalars["GID"][]; // [GID!]!
    };
    deletePetitionField: {
      // args
      fieldId: NexusGenScalars["GID"]; // GID!
      force?: boolean | null; // Boolean
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    deletePetitionFieldComment: {
      // args
      petitionFieldCommentId: NexusGenScalars["GID"]; // GID!
      petitionFieldId: NexusGenScalars["GID"]; // GID!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    deletePetitions: {
      // args
      force?: boolean | null; // Boolean
      ids: NexusGenScalars["GID"][]; // [GID!]!
    };
    editPetitionUserPermission: {
      // args
      permissionType: NexusGenEnums["PetitionUserPermissionType"]; // PetitionUserPermissionType!
      petitionIds: NexusGenScalars["GID"][]; // [GID!]!
      userIds: NexusGenScalars["GID"][]; // [GID!]!
    };
    fileUploadReplyDownloadLink: {
      // args
      petitionId: NexusGenScalars["GID"]; // GID!
      preview?: boolean | null; // Boolean
      replyId: NexusGenScalars["GID"]; // GID!
    };
    markPetitionFieldCommentsAsRead: {
      // args
      petitionFieldCommentIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    publicCompletePetition: {
      // args
      keycode: string; // ID!
    };
    publicCreateFileUploadReply: {
      // args
      data: NexusGenInputs["CreateFileUploadReplyInput"]; // CreateFileUploadReplyInput!
      fieldId: NexusGenScalars["GID"]; // GID!
      keycode: string; // ID!
    };
    publicCreatePetitionFieldComment: {
      // args
      content: string; // String!
      keycode: string; // ID!
      petitionFieldId: NexusGenScalars["GID"]; // GID!
    };
    publicCreateTextReply: {
      // args
      data: NexusGenInputs["CreateTextReplyInput"]; // CreateTextReplyInput!
      fieldId: NexusGenScalars["GID"]; // GID!
      keycode: string; // ID!
    };
    publicDeletePetitionFieldComment: {
      // args
      keycode: string; // ID!
      petitionFieldCommentId: NexusGenScalars["GID"]; // GID!
      petitionFieldId: NexusGenScalars["GID"]; // GID!
    };
    publicDeletePetitionReply: {
      // args
      keycode: string; // ID!
      replyId: NexusGenScalars["GID"]; // GID!
    };
    publicFileUploadReplyComplete: {
      // args
      keycode: string; // ID!
      replyId: NexusGenScalars["GID"]; // GID!
    };
    publicMarkPetitionFieldCommentsAsRead: {
      // args
      keycode: string; // ID!
      petitionFieldCommentIds: NexusGenScalars["GID"][]; // [GID!]!
    };
    publicSubmitUnpublishedComments: {
      // args
      keycode: string; // ID!
    };
    publicUpdatePetitionFieldComment: {
      // args
      content: string; // String!
      keycode: string; // ID!
      petitionFieldCommentId: NexusGenScalars["GID"]; // GID!
      petitionFieldId: NexusGenScalars["GID"]; // GID!
    };
    reactivateAccesses: {
      // args
      accessIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    removePetitionUserPermission: {
      // args
      petitionIds: NexusGenScalars["GID"][]; // [GID!]!
      userIds: NexusGenScalars["GID"][]; // [GID!]!
    };
    sendMessages: {
      // args
      accessIds: NexusGenScalars["GID"][]; // [GID!]!
      body: NexusGenScalars["JSON"]; // JSON!
      petitionId: NexusGenScalars["GID"]; // GID!
      scheduledAt?: NexusGenScalars["DateTime"] | null; // DateTime
      subject: string; // String!
    };
    sendPetition: {
      // args
      body: NexusGenScalars["JSON"]; // JSON!
      contactIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
      remindersConfig?: NexusGenInputs["RemindersConfigInput"] | null; // RemindersConfigInput
      scheduledAt?: NexusGenScalars["DateTime"] | null; // DateTime
      subject: string; // String!
    };
    sendReminders: {
      // args
      accessIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    submitUnpublishedComments: {
      // args
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    switchAutomaticReminders: {
      // args
      accessIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
      remindersConfig?: NexusGenInputs["RemindersConfigInput"] | null; // RemindersConfigInput
      start: boolean; // Boolean!
    };
    transferPetitionOwnership: {
      // args
      petitionIds: NexusGenScalars["GID"][]; // [GID!]!
      userId: NexusGenScalars["GID"]; // GID!
    };
    updateContact: {
      // args
      data: NexusGenInputs["UpdateContactInput"]; // UpdateContactInput!
      id: NexusGenScalars["GID"]; // GID!
    };
    updateFieldPositions: {
      // args
      fieldIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    updateOnboardingStatus: {
      // args
      key: NexusGenEnums["OnboardingKey"]; // OnboardingKey!
      status: NexusGenEnums["OnboardingStatus"]; // OnboardingStatus!
    };
    updatePetition: {
      // args
      data: NexusGenInputs["UpdatePetitionInput"]; // UpdatePetitionInput!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    updatePetitionField: {
      // args
      data: NexusGenInputs["UpdatePetitionFieldInput"]; // UpdatePetitionFieldInput!
      fieldId: NexusGenScalars["GID"]; // GID!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    updatePetitionFieldComment: {
      // args
      content: string; // String!
      petitionFieldCommentId: NexusGenScalars["GID"]; // GID!
      petitionFieldId: NexusGenScalars["GID"]; // GID!
      petitionId: NexusGenScalars["GID"]; // GID!
    };
    updatePetitionFieldRepliesStatus: {
      // args
      petitionFieldId: NexusGenScalars["GID"]; // GID!
      petitionFieldReplyIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
      status: NexusGenEnums["PetitionFieldReplyStatus"]; // PetitionFieldReplyStatus!
    };
    updateUser: {
      // args
      data: NexusGenInputs["UpdateUserInput"]; // UpdateUserInput!
      id: NexusGenScalars["GID"]; // GID!
    };
    validatePetitionFields: {
      // args
      fieldIds: NexusGenScalars["GID"][]; // [GID!]!
      petitionId: NexusGenScalars["GID"]; // GID!
      value: boolean; // Boolean!
    };
  };
  Organization: {
    users: {
      // args
      exclude?: NexusGenScalars["GID"][] | null; // [GID!]
      limit?: number | null; // Int
      offset?: number | null; // Int
      search?: string | null; // String
    };
  };
  Petition: {
    events: {
      // args
      limit?: number | null; // Int
      offset?: number | null; // Int
    };
  };
  Query: {
    access: {
      // args
      keycode: string; // ID!
    };
    contact: {
      // args
      id: NexusGenScalars["GID"]; // GID!
    };
    contacts: {
      // args
      exclude?: NexusGenScalars["GID"][] | null; // [GID!]
      limit?: number | null; // Int
      offset?: number | null; // Int
      search?: string | null; // String
      sortBy?: NexusGenEnums["QueryContacts_OrderBy"][] | null; // [QueryContacts_OrderBy!]
    };
    organization: {
      // args
      id: NexusGenScalars["GID"]; // GID!
    };
    petition: {
      // args
      id: NexusGenScalars["GID"]; // GID!
    };
    petitions: {
      // args
      limit?: number | null; // Int
      locale?: NexusGenEnums["PetitionLocale"] | null; // PetitionLocale
      offset?: number | null; // Int
      search?: string | null; // String
      sortBy?: NexusGenEnums["QueryPetitions_OrderBy"][] | null; // [QueryPetitions_OrderBy!]
      status?: NexusGenEnums["PetitionStatus"] | null; // PetitionStatus
      type?: NexusGenEnums["PetitionBaseType"] | null; // PetitionBaseType
    };
    publicTemplates: {
      // args
      limit?: number | null; // Int
      locale?: NexusGenEnums["PetitionLocale"] | null; // PetitionLocale
      offset?: number | null; // Int
      search?: string | null; // String
    };
  };
}

export interface NexusGenAbstractResolveReturnTypes {
  PublicUserOrContact: "PublicContact" | "PublicUser";
  UserOrPetitionAccess: "PetitionAccess" | "User";
  CreatedAt: "PetitionMessage" | "PetitionReminder";
  PetitionBase: "Petition" | "PetitionTemplate";
  PetitionBaseAndField: "PetitionAndField" | "PetitionTemplateAndField";
  PetitionEvent:
    | "AccessActivatedEvent"
    | "AccessDeactivatedEvent"
    | "AccessOpenedEvent"
    | "CommentDeletedEvent"
    | "CommentPublishedEvent"
    | "MessageCancelledEvent"
    | "MessageScheduledEvent"
    | "MessageSentEvent"
    | "OwnershipTransferredEvent"
    | "PetitionCompletedEvent"
    | "PetitionCreatedEvent"
    | "ReminderSentEvent"
    | "ReplyCreatedEvent"
    | "ReplyDeletedEvent"
    | "UserPermissionAddedEvent"
    | "UserPermissionEditedEvent"
    | "UserPermissionRemovedEvent";
  Timestamps:
    | "Contact"
    | "Organization"
    | "PetitionAccess"
    | "PetitionFieldReply"
    | "PetitionUserPermission"
    | "PublicPetition"
    | "PublicPetitionFieldReply"
    | "User";
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames =
  | "AccessActivatedEvent"
  | "AccessDeactivatedEvent"
  | "AccessOpenedEvent"
  | "CommentDeletedEvent"
  | "CommentPublishedEvent"
  | "Contact"
  | "ContactPagination"
  | "CreateFileUploadReply"
  | "FileUploadReplyDownloadLinkResult"
  | "MessageCancelledEvent"
  | "MessageScheduledEvent"
  | "MessageSentEvent"
  | "Mutation"
  | "Organization"
  | "OwnershipTransferredEvent"
  | "Petition"
  | "PetitionAccess"
  | "PetitionAccessPagination"
  | "PetitionAndField"
  | "PetitionBasePagination"
  | "PetitionCompletedEvent"
  | "PetitionCreatedEvent"
  | "PetitionEventPagination"
  | "PetitionField"
  | "PetitionFieldAndReplies"
  | "PetitionFieldComment"
  | "PetitionFieldReply"
  | "PetitionMessage"
  | "PetitionProgress"
  | "PetitionReminder"
  | "PetitionTemplate"
  | "PetitionTemplateAndField"
  | "PetitionTemplatePagination"
  | "PetitionUserPermission"
  | "PublicContact"
  | "PublicOrganization"
  | "PublicPetition"
  | "PublicPetitionAccess"
  | "PublicPetitionField"
  | "PublicPetitionFieldComment"
  | "PublicPetitionFieldReply"
  | "PublicUser"
  | "Query"
  | "ReminderSentEvent"
  | "RemindersConfig"
  | "ReplyCreatedEvent"
  | "ReplyDeletedEvent"
  | "SendPetitionResult"
  | "User"
  | "UserPagination"
  | "UserPermissionAddedEvent"
  | "UserPermissionEditedEvent"
  | "UserPermissionRemovedEvent";

export type NexusGenInputNames =
  | "CreateContactInput"
  | "CreateFileUploadReplyInput"
  | "CreateTextReplyInput"
  | "RemindersConfigInput"
  | "UpdateContactInput"
  | "UpdatePetitionFieldInput"
  | "UpdatePetitionInput"
  | "UpdateUserInput";

export type NexusGenEnumNames =
  | "ChangePasswordResult"
  | "OnboardingKey"
  | "OnboardingStatus"
  | "OrganizationRole"
  | "OrganizationStatus"
  | "PetitionAccessStatus"
  | "PetitionBaseType"
  | "PetitionFieldReplyStatus"
  | "PetitionFieldType"
  | "PetitionLocale"
  | "PetitionMessageStatus"
  | "PetitionReminderType"
  | "PetitionStatus"
  | "PetitionUserPermissionType"
  | "PetitionUserPermissionTypeRW"
  | "QueryContacts_OrderBy"
  | "QueryPetitions_OrderBy"
  | "Result";

export type NexusGenInterfaceNames =
  | "CreatedAt"
  | "PetitionBase"
  | "PetitionBaseAndField"
  | "PetitionEvent"
  | "Timestamps";

export type NexusGenScalarNames =
  | "Boolean"
  | "DateTime"
  | "Float"
  | "GID"
  | "ID"
  | "Int"
  | "JSON"
  | "JSONObject"
  | "String";

export type NexusGenUnionNames = "PublicUserOrContact" | "UserOrPetitionAccess";

export interface NexusGenTypes {
  context: ctx.ApiContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes["inputNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["scalarNames"];
  allOutputTypes:
    | NexusGenTypes["objectNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["unionNames"]
    | NexusGenTypes["interfaceNames"]
    | NexusGenTypes["scalarNames"];
  allNamedTypes:
    | NexusGenTypes["allInputTypes"]
    | NexusGenTypes["allOutputTypes"];
  abstractTypes: NexusGenTypes["interfaceNames"] | NexusGenTypes["unionNames"];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>;
    /**
     * Run validation for the args of this type. Any errors thrown here will
     * prevent the resolve method from executing.
     */
    validateArgs?: FieldValidateArgsResolver<TypeName, FieldName>;
  }
  interface NexusGenPluginSchemaConfig {}
}
