/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as ctx from "../context";
import * as db from "../db/__types";
import * as events from "./backing/events";
import { FieldAuthorizeResolver } from "@nexus/schema/dist/plugins/fieldAuthorizePlugin";
import { FieldValidateArgsResolver } from "./helpers/validateArgsPlugin";
import { core } from "@nexus/schema";
import { PaginationFieldConfig } from "./helpers/paginationPlugin";
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    datetime<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<"inputTypes", TypeName, FieldName>
      >
    ): void; // "DateTime";
    jsonObject<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<"inputTypes", TypeName, FieldName>
      >
    ): void; // "JSONObject";
    json<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.ScalarInputFieldConfig<
        core.GetGen3<"inputTypes", TypeName, FieldName>
      >
    ): void; // "JSON";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    datetime<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "DateTime";
    jsonObject<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "JSONObject";
    json<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "JSON";
    paginationField<
      FieldName extends string,
      PaginationType extends
        | core.GetGen<"allOutputTypes", string>
        | core.AllNexusOutputTypeDefs
    >(
      fieldName: FieldName,
      config: PaginationFieldConfig<TypeName, FieldName, PaginationType>
    ): void;
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateContactInput: {
    // input type
    email: string; // String!
    firstName?: string | null; // String
    lastName?: string | null; // String
  };
  CreateFileUploadReplyInput: {
    // input type
    contentType: string; // String!
    filename: string; // String!
    size: number; // Int!
  };
  CreateTextReplyInput: {
    // input type
    text: string; // String!
  };
  RemindersConfigInput: {
    // input type
    offset: number; // Int!
    time: string; // String!
    timezone: string; // String!
    weekdaysOnly: boolean; // Boolean!
  };
  UpdateContactInput: {
    // input type
    firstName?: string | null; // String
    lastName?: string | null; // String
  };
  UpdatePetitionFieldInput: {
    // input type
    description?: string | null; // String
    multiple?: boolean | null; // Boolean
    optional?: boolean | null; // Boolean
    options?: { [key: string]: any } | null; // JSONObject
    title?: string | null; // String
  };
  UpdatePetitionInput: {
    // input type
    deadline?: Date | null; // DateTime
    emailBody?: any | null; // JSON
    emailSubject?: string | null; // String
    locale?: NexusGenEnums["PetitionLocale"] | null; // PetitionLocale
    name?: string | null; // String
    remindersConfig?: NexusGenInputs["RemindersConfigInput"] | null; // RemindersConfigInput
  };
  UpdateUserInput: {
    // input type
    firstName?: string | null; // String
    lastName?: string | null; // String
  };
}

export interface NexusGenEnums {
  ChangePasswordResult:
    | "INCORRECT_PASSWORD"
    | "INVALID_NEW_PASSWORD"
    | "SUCCESS";
  OnboardingKey:
    | "PETITION_ACTIVITY"
    | "PETITION_COMPOSE"
    | "PETITION_REVIEW"
    | "PETITIONS_LIST";
  OnboardingStatus: "FINISHED" | "SKIPPED";
  OrganizationRole: "ADMIN" | "NORMAL";
  OrganizationStatus: db.OrganizationStatus;
  PetitionAccessStatus: db.PetitionAccessStatus;
  PetitionFieldType: db.PetitionFieldType;
  PetitionLocale: "en" | "es";
  PetitionMessageStatus: db.PetitionMessageStatus;
  PetitionReminderType: db.PetitionReminderType;
  PetitionStatus: db.PetitionStatus;
  QueryContacts_OrderBy:
    | "createdAt_ASC"
    | "createdAt_DESC"
    | "email_ASC"
    | "email_DESC"
    | "firstName_ASC"
    | "firstName_DESC"
    | "fullName_ASC"
    | "fullName_DESC"
    | "lastName_ASC"
    | "lastName_DESC";
  QueryPetitions_OrderBy:
    | "createdAt_ASC"
    | "createdAt_DESC"
    | "name_ASC"
    | "name_DESC";
  Result: "FAILURE" | "SUCCESS";
}

export interface NexusGenRootTypes {
  AccessActivatedEvent: events.AccessActivatedEvent;
  AccessDeactivatedEvent: events.AccessDeactivatedEvent;
  AccessOpenedEvent: events.AccessOpenedEvent;
  Contact: db.Contact;
  ContactPagination: {
    // root type
    items: NexusGenRootTypes["Contact"][]; // [Contact!]!
    totalCount: number; // Int!
  };
  CreateFileUploadReply: {
    // root type
    endpoint: string; // String!
    reply: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
  };
  FileUploadReplyDownloadLinkResult: {
    // root type
    result: NexusGenEnums["Result"]; // Result!
    url?: string | null; // String
  };
  MessageCancelledEvent: events.MessageCancelledEvent;
  MessageProcessedEvent: events.MessageProcessedEvent;
  MessageScheduledEvent: events.MessageScheduledEvent;
  Mutation: {};
  Organization: db.Organization;
  Petition: db.Petition;
  PetitionAccess: db.PetitionAccess;
  PetitionAccessPagination: {
    // root type
    items: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    totalCount: number; // Int!
  };
  PetitionAndField: {
    // root type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    petition: NexusGenRootTypes["Petition"]; // Petition!
  };
  PetitionAndFields: {
    // root type
    fields: NexusGenRootTypes["PetitionField"][]; // [PetitionField!]!
    petition: NexusGenRootTypes["Petition"]; // Petition!
  };
  PetitionCompletedEvent: events.PetitionCompletedEvent;
  PetitionCreatedEvent: events.PetitionCreatedEvent;
  PetitionEventPagination: {
    // root type
    items: NexusGenRootTypes["PetitionEvent"][]; // [PetitionEvent!]!
    totalCount: number; // Int!
  };
  PetitionField: db.PetitionField;
  PetitionFieldReply: db.PetitionFieldReply;
  PetitionMessage: db.PetitionMessage;
  PetitionPagination: {
    // root type
    items: NexusGenRootTypes["Petition"][]; // [Petition!]!
    totalCount: number; // Int!
  };
  PetitionProgress: {
    // root type
    optional: number; // Int!
    replied: number; // Int!
    total: number; // Int!
    validated: number; // Int!
  };
  PetitionReminder: db.PetitionReminder;
  PublicOrganization: db.Organization;
  PublicPetition: db.Petition;
  PublicPetitionAccess: db.PetitionAccess;
  PublicPetitionField: db.PetitionField;
  PublicPetitionFieldReply: db.PetitionFieldReply;
  PublicUser: db.User;
  Query: {};
  ReminderProcessedEvent: events.ReminderProcessedEvent;
  RemindersConfig: {
    // root type
    offset: number; // Int!
    time: string; // String!
    timezone: string; // String!
    weekdaysOnly: boolean; // Boolean!
  };
  ReplyCreatedEvent: events.ReplyCreatedEvent;
  ReplyDeletedEvent: events.ReplyDeletedEvent;
  SendPetitionResult: {
    // root type
    petition?: NexusGenRootTypes["Petition"] | null; // Petition
    result: NexusGenEnums["Result"]; // Result!
  };
  User: db.User;
  UserPagination: {
    // root type
    items: NexusGenRootTypes["User"][]; // [User!]!
    totalCount: number; // Int!
  };
  CreatedAt:
    | NexusGenRootTypes["PetitionMessage"]
    | NexusGenRootTypes["PetitionReminder"];
  PetitionEvent: events.PetitionEvent;
  Timestamps:
    | NexusGenRootTypes["Contact"]
    | NexusGenRootTypes["Organization"]
    | NexusGenRootTypes["Petition"]
    | NexusGenRootTypes["PetitionAccess"]
    | NexusGenRootTypes["PetitionFieldReply"]
    | NexusGenRootTypes["PublicPetition"]
    | NexusGenRootTypes["PublicPetitionFieldReply"]
    | NexusGenRootTypes["User"];
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: Date;
  JSON: any;
  JSONObject: { [key: string]: any };
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  CreateContactInput: NexusGenInputs["CreateContactInput"];
  CreateFileUploadReplyInput: NexusGenInputs["CreateFileUploadReplyInput"];
  CreateTextReplyInput: NexusGenInputs["CreateTextReplyInput"];
  RemindersConfigInput: NexusGenInputs["RemindersConfigInput"];
  UpdateContactInput: NexusGenInputs["UpdateContactInput"];
  UpdatePetitionFieldInput: NexusGenInputs["UpdatePetitionFieldInput"];
  UpdatePetitionInput: NexusGenInputs["UpdatePetitionInput"];
  UpdateUserInput: NexusGenInputs["UpdateUserInput"];
  ChangePasswordResult: NexusGenEnums["ChangePasswordResult"];
  OnboardingKey: NexusGenEnums["OnboardingKey"];
  OnboardingStatus: NexusGenEnums["OnboardingStatus"];
  OrganizationRole: NexusGenEnums["OrganizationRole"];
  OrganizationStatus: NexusGenEnums["OrganizationStatus"];
  PetitionAccessStatus: NexusGenEnums["PetitionAccessStatus"];
  PetitionFieldType: NexusGenEnums["PetitionFieldType"];
  PetitionLocale: NexusGenEnums["PetitionLocale"];
  PetitionMessageStatus: NexusGenEnums["PetitionMessageStatus"];
  PetitionReminderType: NexusGenEnums["PetitionReminderType"];
  PetitionStatus: NexusGenEnums["PetitionStatus"];
  QueryContacts_OrderBy: NexusGenEnums["QueryContacts_OrderBy"];
  QueryPetitions_OrderBy: NexusGenEnums["QueryPetitions_OrderBy"];
  Result: NexusGenEnums["Result"];
}

export interface NexusGenFieldTypes {
  AccessActivatedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: Date; // DateTime!
    id: string; // ID!
    user: NexusGenRootTypes["User"]; // User!
  };
  AccessDeactivatedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: Date; // DateTime!
    id: string; // ID!
    user: NexusGenRootTypes["User"]; // User!
  };
  AccessOpenedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: Date; // DateTime!
    id: string; // ID!
  };
  Contact: {
    // field return type
    accesses: NexusGenRootTypes["PetitionAccessPagination"]; // PetitionAccessPagination!
    createdAt: Date; // DateTime!
    email: string; // String!
    firstName: string | null; // String
    fullName: string | null; // String
    id: string; // ID!
    lastName: string | null; // String
    updatedAt: Date; // DateTime!
  };
  ContactPagination: {
    // field return type
    items: NexusGenRootTypes["Contact"][]; // [Contact!]!
    totalCount: number; // Int!
  };
  CreateFileUploadReply: {
    // field return type
    endpoint: string; // String!
    reply: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
  };
  FileUploadReplyDownloadLinkResult: {
    // field return type
    result: NexusGenEnums["Result"]; // Result!
    url: string | null; // String
  };
  MessageCancelledEvent: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
    message: NexusGenRootTypes["PetitionMessage"]; // PetitionMessage!
  };
  MessageProcessedEvent: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
    message: NexusGenRootTypes["PetitionMessage"]; // PetitionMessage!
  };
  MessageScheduledEvent: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
    message: NexusGenRootTypes["PetitionMessage"]; // PetitionMessage!
  };
  Mutation: {
    // field return type
    cancelScheduledMessages: NexusGenRootTypes["PetitionMessage"] | null; // PetitionMessage
    changePassword: NexusGenEnums["ChangePasswordResult"]; // ChangePasswordResult!
    clonePetition: NexusGenRootTypes["Petition"]; // Petition!
    createContact: NexusGenRootTypes["Contact"]; // Contact!
    createPetition: NexusGenRootTypes["Petition"]; // Petition!
    createPetitionField: NexusGenRootTypes["PetitionAndField"]; // PetitionAndField!
    deleteContacts: NexusGenEnums["Result"]; // Result!
    deletePetitionField: NexusGenRootTypes["Petition"]; // Petition!
    deletePetitions: NexusGenEnums["Result"]; // Result!
    fileUploadReplyDownloadLink: NexusGenRootTypes["FileUploadReplyDownloadLinkResult"]; // FileUploadReplyDownloadLinkResult!
    publicCompletePetition: NexusGenRootTypes["PublicPetition"]; // PublicPetition!
    publicCreateFileUploadReply: NexusGenRootTypes["CreateFileUploadReply"]; // CreateFileUploadReply!
    publicCreateTextReply: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
    publicDeletePetitionReply: NexusGenEnums["Result"]; // Result!
    publicFileUploadReplyComplete: NexusGenRootTypes["PublicPetitionFieldReply"]; // PublicPetitionFieldReply!
    sendPetition: NexusGenRootTypes["SendPetitionResult"]; // SendPetitionResult!
    sendReminders: NexusGenEnums["Result"]; // Result!
    updateContact: NexusGenRootTypes["Contact"]; // Contact!
    updateFieldPositions: NexusGenRootTypes["Petition"]; // Petition!
    updateOnboardingStatus: NexusGenRootTypes["User"]; // User!
    updatePetition: NexusGenRootTypes["Petition"]; // Petition!
    updatePetitionField: NexusGenRootTypes["PetitionAndField"]; // PetitionAndField!
    updateUser: NexusGenRootTypes["User"]; // User!
    validatePetitionFields: NexusGenRootTypes["PetitionAndFields"]; // PetitionAndFields!
  };
  Organization: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
    identifier: string; // String!
    name: string; // String!
    status: NexusGenEnums["OrganizationStatus"]; // OrganizationStatus!
    updatedAt: Date; // DateTime!
    users: NexusGenRootTypes["UserPagination"]; // UserPagination!
  };
  Petition: {
    // field return type
    accesses: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    createdAt: Date; // DateTime!
    customRef: string | null; // String
    deadline: Date | null; // DateTime
    emailBody: any | null; // JSON
    emailSubject: string | null; // String
    events: NexusGenRootTypes["PetitionEventPagination"]; // PetitionEventPagination!
    fieldCount: number; // Int!
    fields: NexusGenRootTypes["PetitionField"][]; // [PetitionField!]!
    id: string; // ID!
    locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
    name: string | null; // String
    progress: NexusGenRootTypes["PetitionProgress"]; // PetitionProgress!
    recipients: Array<NexusGenRootTypes["Contact"] | null>; // [Contact]!
    remindersConfig: NexusGenRootTypes["RemindersConfig"] | null; // RemindersConfig
    status: NexusGenEnums["PetitionStatus"]; // PetitionStatus!
    updatedAt: Date; // DateTime!
  };
  PetitionAccess: {
    // field return type
    contact: NexusGenRootTypes["Contact"] | null; // Contact
    createdAt: Date; // DateTime!
    granter: NexusGenRootTypes["User"] | null; // User
    id: string; // ID!
    nextReminderAt: Date | null; // DateTime
    petition: NexusGenRootTypes["Petition"] | null; // Petition
    remindersConfig: NexusGenRootTypes["RemindersConfig"] | null; // RemindersConfig
    status: NexusGenEnums["PetitionAccessStatus"]; // PetitionAccessStatus!
    updatedAt: Date; // DateTime!
  };
  PetitionAccessPagination: {
    // field return type
    items: NexusGenRootTypes["PetitionAccess"][]; // [PetitionAccess!]!
    totalCount: number; // Int!
  };
  PetitionAndField: {
    // field return type
    field: NexusGenRootTypes["PetitionField"]; // PetitionField!
    petition: NexusGenRootTypes["Petition"]; // Petition!
  };
  PetitionAndFields: {
    // field return type
    fields: NexusGenRootTypes["PetitionField"][]; // [PetitionField!]!
    petition: NexusGenRootTypes["Petition"]; // Petition!
  };
  PetitionCompletedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: Date; // DateTime!
    id: string; // ID!
  };
  PetitionCreatedEvent: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
    user: NexusGenRootTypes["User"]; // User!
  };
  PetitionEventPagination: {
    // field return type
    items: NexusGenRootTypes["PetitionEvent"][]; // [PetitionEvent!]!
    totalCount: number; // Int!
  };
  PetitionField: {
    // field return type
    description: string | null; // String
    id: string; // ID!
    multiple: boolean; // Boolean!
    optional: boolean; // Boolean!
    options: { [key: string]: any } | null; // JSONObject
    replies: NexusGenRootTypes["PetitionFieldReply"][]; // [PetitionFieldReply!]!
    title: string | null; // String
    type: NexusGenEnums["PetitionFieldType"]; // PetitionFieldType!
    validated: boolean; // Boolean!
  };
  PetitionFieldReply: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"] | null; // PetitionAccess
    content: { [key: string]: any }; // JSONObject!
    createdAt: Date; // DateTime!
    id: string; // ID!
    updatedAt: Date; // DateTime!
  };
  PetitionMessage: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    bouncedAt: Date | null; // DateTime
    createdAt: Date; // DateTime!
    deliveredAt: Date | null; // DateTime
    emailBody: any | null; // JSON
    emailSubject: any | null; // JSON
    id: string; // ID!
    openedAt: Date | null; // DateTime
    scheduledAt: Date | null; // DateTime
    sender: NexusGenRootTypes["User"]; // User!
    sentAt: Date | null; // DateTime
    status: NexusGenEnums["PetitionMessageStatus"]; // PetitionMessageStatus!
  };
  PetitionPagination: {
    // field return type
    items: NexusGenRootTypes["Petition"][]; // [Petition!]!
    totalCount: number; // Int!
  };
  PetitionProgress: {
    // field return type
    optional: number; // Int!
    replied: number; // Int!
    total: number; // Int!
    validated: number; // Int!
  };
  PetitionReminder: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: Date; // DateTime!
    id: string; // ID!
    sender: NexusGenRootTypes["User"] | null; // User
    type: NexusGenEnums["PetitionReminderType"]; // PetitionReminderType!
  };
  PublicOrganization: {
    // field return type
    id: string; // ID!
    identifier: string; // String!
    name: string; // String!
  };
  PublicPetition: {
    // field return type
    createdAt: Date; // DateTime!
    deadline: Date | null; // DateTime
    fields: NexusGenRootTypes["PublicPetitionField"][]; // [PublicPetitionField!]!
    id: string; // ID!
    locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
    status: NexusGenEnums["PetitionStatus"]; // PetitionStatus!
    updatedAt: Date; // DateTime!
  };
  PublicPetitionAccess: {
    // field return type
    granter: NexusGenRootTypes["PublicUser"] | null; // PublicUser
    petition: NexusGenRootTypes["PublicPetition"] | null; // PublicPetition
  };
  PublicPetitionField: {
    // field return type
    description: string | null; // String
    id: string; // ID!
    multiple: boolean; // Boolean!
    optional: boolean; // Boolean!
    options: { [key: string]: any } | null; // JSONObject
    replies: NexusGenRootTypes["PublicPetitionFieldReply"][]; // [PublicPetitionFieldReply!]!
    title: string | null; // String
    type: NexusGenEnums["PetitionFieldType"]; // PetitionFieldType!
    validated: boolean; // Boolean!
  };
  PublicPetitionFieldReply: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
    publicContent: { [key: string]: any }; // JSONObject!
    updatedAt: Date; // DateTime!
  };
  PublicUser: {
    // field return type
    email: string; // String!
    firstName: string | null; // String
    fullName: string | null; // String
    id: string; // ID!
    lastName: string | null; // String
    organization: NexusGenRootTypes["PublicOrganization"]; // PublicOrganization!
  };
  Query: {
    // field return type
    access: NexusGenRootTypes["PublicPetitionAccess"] | null; // PublicPetitionAccess
    contact: NexusGenRootTypes["Contact"] | null; // Contact
    contacts: NexusGenRootTypes["ContactPagination"]; // ContactPagination!
    me: NexusGenRootTypes["User"]; // User!
    organization: NexusGenRootTypes["Organization"] | null; // Organization
    petition: NexusGenRootTypes["Petition"] | null; // Petition
    petitions: NexusGenRootTypes["PetitionPagination"]; // PetitionPagination!
  };
  ReminderProcessedEvent: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
    reminder: NexusGenRootTypes["PetitionReminder"]; // PetitionReminder!
  };
  RemindersConfig: {
    // field return type
    offset: number; // Int!
    time: string; // String!
    timezone: string; // String!
    weekdaysOnly: boolean; // Boolean!
  };
  ReplyCreatedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: Date; // DateTime!
    field: NexusGenRootTypes["PetitionField"] | null; // PetitionField
    id: string; // ID!
    reply: NexusGenRootTypes["PetitionFieldReply"] | null; // PetitionFieldReply
  };
  ReplyDeletedEvent: {
    // field return type
    access: NexusGenRootTypes["PetitionAccess"]; // PetitionAccess!
    createdAt: Date; // DateTime!
    field: NexusGenRootTypes["PetitionField"] | null; // PetitionField
    id: string; // ID!
    reply: NexusGenRootTypes["PetitionFieldReply"] | null; // PetitionFieldReply
  };
  SendPetitionResult: {
    // field return type
    petition: NexusGenRootTypes["Petition"] | null; // Petition
    result: NexusGenEnums["Result"]; // Result!
  };
  User: {
    // field return type
    createdAt: Date; // DateTime!
    email: string; // String!
    firstName: string | null; // String
    fullName: string | null; // String
    id: string; // ID!
    lastName: string | null; // String
    onboardingStatus: { [key: string]: any }; // JSONObject!
    organization: NexusGenRootTypes["Organization"]; // Organization!
    organizationRole: NexusGenEnums["OrganizationRole"]; // OrganizationRole!
    updatedAt: Date; // DateTime!
  };
  UserPagination: {
    // field return type
    items: NexusGenRootTypes["User"][]; // [User!]!
    totalCount: number; // Int!
  };
  CreatedAt: {
    // field return type
    createdAt: Date; // DateTime!
  };
  PetitionEvent: {
    // field return type
    createdAt: Date; // DateTime!
    id: string; // ID!
  };
  Timestamps: {
    // field return type
    createdAt: Date; // DateTime!
    updatedAt: Date; // DateTime!
  };
}

export interface NexusGenArgTypes {
  Contact: {
    accesses: {
      // args
      limit?: number | null; // Int
      offset?: number | null; // Int
    };
  };
  Mutation: {
    cancelScheduledMessages: {
      // args
      messageId: string; // ID!
      petitionId: string; // ID!
    };
    changePassword: {
      // args
      newPassword: string; // String!
      password: string; // String!
    };
    clonePetition: {
      // args
      name?: string | null; // String
      petitionId: string; // ID!
    };
    createContact: {
      // args
      data: NexusGenInputs["CreateContactInput"]; // CreateContactInput!
    };
    createPetition: {
      // args
      locale: NexusGenEnums["PetitionLocale"]; // PetitionLocale!
      name: string; // String!
    };
    createPetitionField: {
      // args
      petitionId: string; // ID!
      type: NexusGenEnums["PetitionFieldType"]; // PetitionFieldType!
    };
    deleteContacts: {
      // args
      ids: string[]; // [ID!]!
    };
    deletePetitionField: {
      // args
      fieldId: string; // ID!
      petitionId: string; // ID!
    };
    deletePetitions: {
      // args
      ids: string[]; // [ID!]!
    };
    fileUploadReplyDownloadLink: {
      // args
      petitionId: string; // ID!
      replyId: string; // ID!
    };
    publicCompletePetition: {
      // args
      keycode: string; // ID!
    };
    publicCreateFileUploadReply: {
      // args
      data: NexusGenInputs["CreateFileUploadReplyInput"]; // CreateFileUploadReplyInput!
      fieldId: string; // ID!
      keycode: string; // ID!
    };
    publicCreateTextReply: {
      // args
      data: NexusGenInputs["CreateTextReplyInput"]; // CreateTextReplyInput!
      fieldId: string; // ID!
      keycode: string; // ID!
    };
    publicDeletePetitionReply: {
      // args
      keycode: string; // ID!
      replyId: string; // ID!
    };
    publicFileUploadReplyComplete: {
      // args
      keycode: string; // ID!
      replyId: string; // ID!
    };
    sendPetition: {
      // args
      contactIds: string[]; // [ID!]!
      petitionId: string; // ID!
      scheduledAt?: Date | null; // DateTime
    };
    sendReminders: {
      // args
      accessIds: string[]; // [ID!]!
      petitionId: string; // ID!
    };
    updateContact: {
      // args
      data: NexusGenInputs["UpdateContactInput"]; // UpdateContactInput!
      id: string; // ID!
    };
    updateFieldPositions: {
      // args
      fieldIds: string[]; // [ID!]!
      petitionId: string; // ID!
    };
    updateOnboardingStatus: {
      // args
      key: NexusGenEnums["OnboardingKey"]; // OnboardingKey!
      status: NexusGenEnums["OnboardingStatus"]; // OnboardingStatus!
    };
    updatePetition: {
      // args
      data: NexusGenInputs["UpdatePetitionInput"]; // UpdatePetitionInput!
      petitionId: string; // ID!
    };
    updatePetitionField: {
      // args
      data: NexusGenInputs["UpdatePetitionFieldInput"]; // UpdatePetitionFieldInput!
      fieldId: string; // ID!
      petitionId: string; // ID!
    };
    updateUser: {
      // args
      data: NexusGenInputs["UpdateUserInput"]; // UpdateUserInput!
      id: string; // ID!
    };
    validatePetitionFields: {
      // args
      fieldIds: string[]; // [ID!]!
      petitionId: string; // ID!
      value: boolean; // Boolean!
    };
  };
  Organization: {
    users: {
      // args
      limit?: number | null; // Int
      offset?: number | null; // Int
    };
  };
  Petition: {
    events: {
      // args
      limit?: number | null; // Int
      offset?: number | null; // Int
    };
  };
  Query: {
    access: {
      // args
      keycode: string; // ID!
    };
    contact: {
      // args
      id: string; // ID!
    };
    contacts: {
      // args
      exclude?: string[] | null; // [ID!]
      limit?: number | null; // Int
      offset?: number | null; // Int
      search?: string | null; // String
      sortBy?: NexusGenEnums["QueryContacts_OrderBy"][] | null; // [QueryContacts_OrderBy!]
    };
    organization: {
      // args
      id: string; // ID!
    };
    petition: {
      // args
      id: string; // ID!
    };
    petitions: {
      // args
      limit?: number | null; // Int
      offset?: number | null; // Int
      search?: string | null; // String
      sortBy?: NexusGenEnums["QueryPetitions_OrderBy"][] | null; // [QueryPetitions_OrderBy!]
      status?: NexusGenEnums["PetitionStatus"] | null; // PetitionStatus
    };
  };
}

export interface NexusGenAbstractResolveReturnTypes {
  CreatedAt: "PetitionMessage" | "PetitionReminder";
  PetitionEvent:
    | "AccessActivatedEvent"
    | "AccessDeactivatedEvent"
    | "AccessOpenedEvent"
    | "MessageCancelledEvent"
    | "MessageProcessedEvent"
    | "MessageScheduledEvent"
    | "PetitionCompletedEvent"
    | "PetitionCreatedEvent"
    | "ReminderProcessedEvent"
    | "ReplyCreatedEvent"
    | "ReplyDeletedEvent";
  Timestamps:
    | "Contact"
    | "Organization"
    | "Petition"
    | "PetitionAccess"
    | "PetitionFieldReply"
    | "PublicPetition"
    | "PublicPetitionFieldReply"
    | "User";
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames =
  | "AccessActivatedEvent"
  | "AccessDeactivatedEvent"
  | "AccessOpenedEvent"
  | "Contact"
  | "ContactPagination"
  | "CreateFileUploadReply"
  | "FileUploadReplyDownloadLinkResult"
  | "MessageCancelledEvent"
  | "MessageProcessedEvent"
  | "MessageScheduledEvent"
  | "Mutation"
  | "Organization"
  | "Petition"
  | "PetitionAccess"
  | "PetitionAccessPagination"
  | "PetitionAndField"
  | "PetitionAndFields"
  | "PetitionCompletedEvent"
  | "PetitionCreatedEvent"
  | "PetitionEventPagination"
  | "PetitionField"
  | "PetitionFieldReply"
  | "PetitionMessage"
  | "PetitionPagination"
  | "PetitionProgress"
  | "PetitionReminder"
  | "PublicOrganization"
  | "PublicPetition"
  | "PublicPetitionAccess"
  | "PublicPetitionField"
  | "PublicPetitionFieldReply"
  | "PublicUser"
  | "Query"
  | "ReminderProcessedEvent"
  | "RemindersConfig"
  | "ReplyCreatedEvent"
  | "ReplyDeletedEvent"
  | "SendPetitionResult"
  | "User"
  | "UserPagination";

export type NexusGenInputNames =
  | "CreateContactInput"
  | "CreateFileUploadReplyInput"
  | "CreateTextReplyInput"
  | "RemindersConfigInput"
  | "UpdateContactInput"
  | "UpdatePetitionFieldInput"
  | "UpdatePetitionInput"
  | "UpdateUserInput";

export type NexusGenEnumNames =
  | "ChangePasswordResult"
  | "OnboardingKey"
  | "OnboardingStatus"
  | "OrganizationRole"
  | "OrganizationStatus"
  | "PetitionAccessStatus"
  | "PetitionFieldType"
  | "PetitionLocale"
  | "PetitionMessageStatus"
  | "PetitionReminderType"
  | "PetitionStatus"
  | "QueryContacts_OrderBy"
  | "QueryPetitions_OrderBy"
  | "Result";

export type NexusGenInterfaceNames =
  | "CreatedAt"
  | "PetitionEvent"
  | "Timestamps";

export type NexusGenScalarNames =
  | "Boolean"
  | "DateTime"
  | "Float"
  | "ID"
  | "Int"
  | "JSON"
  | "JSONObject"
  | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: ctx.ApiContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes["inputNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["scalarNames"];
  allOutputTypes:
    | NexusGenTypes["objectNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["unionNames"]
    | NexusGenTypes["interfaceNames"]
    | NexusGenTypes["scalarNames"];
  allNamedTypes:
    | NexusGenTypes["allInputTypes"]
    | NexusGenTypes["allOutputTypes"];
  abstractTypes: NexusGenTypes["interfaceNames"] | NexusGenTypes["unionNames"];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>;
    /**
     * Run validation for the args of this type. Any errors thrown here will
     * prevent the resolve method from executing.
     */
    validateArgs?: FieldValidateArgsResolver<TypeName, FieldName>;
  }
  interface NexusGenPluginSchemaConfig {}
}
