export const notificationsMock = [
  {
    id: "0",
    type: "COMMENT_CREATED",
    title: "KYC_Cuatrecasas_2345",
    body: "Lucas Ramírez ha escrito un comentario en el campo “Adjunta la fotocopia de tu DNI/NIE.”",
    timestamp: new Date().getTime(),
    isRead: true,
    meta: {},
  },
  {
    id: "1",
    type: "COMMENT_CREATED",
    title: "KYC_Cuatrecasas_2345",
    body: "Lucas Ramírez ha escrito un comentario en el campo “Adjunta la fotocopia de tu DNI/NIE texto más largo”",
    timestamp: new Date().getTime(),
    isRead: true,
    meta: {},
  },
  {
    id: "2",
    type: "PETITION_COMPLETED",
    title: "KYC_Cuatrecasas_234524",
    body: "Nathan Drake completó la petición.",
    timestamp: new Date().getTime(),
    isRead: false,
    meta: {},
  },
  {
    id: "3",
    type: "SIGNATURE_COMPLETED",
    title: "KYC_Cuatrecasas_2aAdc24-213",
    body: "Óscar Mayer ha completado la firma digital.",
    timestamp: new Date().getTime(),
    isRead: false,
    meta: {},
  },
  {
    id: "4",
    type: "SIGNATURE_CANCELLED",
    title: "KYC_Cuatrecasas_2345 Enviada a Pepito Castañas",
    body: "Jordi García canceló la firma digital.",
    timestamp: new Date().getTime(),
    isRead: true,
    meta: {},
  },
  {
    id: "5",
    type: "PETITION_SHARED",
    title: "KYC_Cuatrecasas_2345",
    body: "Juan Fernández te ha compartido la petición como editor. ",
    timestamp: new Date().getTime(),
    isRead: true,
    meta: {},
  },
  {
    id: "6",
    type: "PETITION_SHARED",
    title: "KYC_Cuatrecasas_2345",
    body: "Juan Fernández ha compartido al grupo Unidad Técnica al que perteneces la petición.",
    timestamp: new Date().getTime(),
    isRead: true,
    meta: {},
  },
  {
    id: "7",
    type: "MESSAGE_EMAIL_BOUNCED",
    title: "KYC_Cuatrecasas_2345",
    body: "Error al enviar la petición a Fullname destinatario (destinatario@sumail.com).",
    timestamp: new Date().getTime(),
    isRead: false,
    meta: {},
  },
] as any[];

export const unreadedNotificationsMock = notificationsMock.filter(
  (n) => !n.isRead
);
