export interface PossibleTypesResultData {
  possibleTypes: {
    [key: string]: string[];
  };
}
const result: PossibleTypesResultData = {
  possibleTypes: {
    BackgroundCheckEntityDetails: [
      "BackgroundCheckEntityDetailsCompany",
      "BackgroundCheckEntityDetailsPerson",
    ],
    BackgroundCheckEntitySearchSchema: [
      "BackgroundCheckEntitySearchCompany",
      "BackgroundCheckEntitySearchPerson",
    ],
    CreatedAt: [
      "PetitionFieldAttachment",
      "PetitionMessage",
      "PetitionReminder",
      "UserAuthenticationToken",
    ],
    DowJonesKycEntityProfileResult: [
      "DowJonesKycEntityProfileResultEntity",
      "DowJonesKycEntityProfileResultPerson",
    ],
    DowJonesKycEntitySearchResult: [
      "DowJonesKycEntitySearchResultEntity",
      "DowJonesKycEntitySearchResultPerson",
    ],
    EventSubscription: ["PetitionEventSubscription", "ProfileEventSubscription"],
    IOrgIntegration: ["OrgIntegration", "SignatureOrgIntegration"],
    PetitionBase: ["Petition", "PetitionTemplate"],
    PetitionBaseOrFolder: ["Petition", "PetitionFolder", "PetitionTemplate"],
    PetitionEvent: [
      "AccessActivatedEvent",
      "AccessActivatedFromPublicPetitionLinkEvent",
      "AccessDeactivatedEvent",
      "AccessDelegatedEvent",
      "AccessOpenedEvent",
      "CommentDeletedEvent",
      "CommentPublishedEvent",
      "GroupPermissionAddedEvent",
      "GroupPermissionEditedEvent",
      "GroupPermissionRemovedEvent",
      "MessageCancelledEvent",
      "MessageScheduledEvent",
      "MessageSentEvent",
      "OwnershipTransferredEvent",
      "PetitionAnonymizedEvent",
      "PetitionClonedEvent",
      "PetitionClosedEvent",
      "PetitionClosedNotifiedEvent",
      "PetitionCompletedEvent",
      "PetitionCreatedEvent",
      "PetitionDeletedEvent",
      "PetitionMessageBouncedEvent",
      "PetitionReminderBouncedEvent",
      "PetitionReopenedEvent",
      "PetitionTaggedEvent",
      "PetitionUntaggedEvent",
      "ProfileAssociatedEvent",
      "ProfileDisassociatedEvent",
      "RecipientSignedEvent",
      "ReminderSentEvent",
      "RemindersOptOutEvent",
      "ReplyCreatedEvent",
      "ReplyDeletedEvent",
      "ReplyStatusChangedEvent",
      "ReplyUpdatedEvent",
      "SignatureCancelledEvent",
      "SignatureCompletedEvent",
      "SignatureDeliveredEvent",
      "SignatureOpenedEvent",
      "SignatureReminderEvent",
      "SignatureStartedEvent",
      "TemplateUsedEvent",
      "UserPermissionAddedEvent",
      "UserPermissionEditedEvent",
      "UserPermissionRemovedEvent",
    ],
    PetitionFieldCommentMention: [
      "PetitionFieldCommentUserGroupMention",
      "PetitionFieldCommentUserMention",
    ],
    PetitionPermission: ["PetitionUserGroupPermission", "PetitionUserPermission"],
    PetitionUserNotification: [
      "AccessActivatedFromPublicPetitionLinkUserNotification",
      "CommentCreatedUserNotification",
      "MessageEmailBouncedUserNotification",
      "PetitionCompletedUserNotification",
      "PetitionSharedUserNotification",
      "ReminderEmailBouncedUserNotification",
      "RemindersOptOutNotification",
      "SignatureCancelledUserNotification",
      "SignatureCompletedUserNotification",
    ],
    ProfileEvent: [
      "PetitionAssociatedEvent",
      "PetitionDisassociatedEvent",
      "ProfileAnonymizedEvent",
      "ProfileClosedEvent",
      "ProfileCreatedEvent",
      "ProfileFieldExpiryUpdatedEvent",
      "ProfileFieldFileAddedEvent",
      "ProfileFieldFileRemovedEvent",
      "ProfileFieldValueUpdatedEvent",
      "ProfileReopenedEvent",
      "ProfileScheduledForDeletionEvent",
      "ProfileUpdatedEvent",
    ],
    ProfileFieldResponse: ["ProfileFieldFile", "ProfileFieldValue"],
    PublicUserOrContact: ["PublicContact", "PublicUser"],
    TemplateDefaultPermission: [
      "TemplateDefaultUserGroupPermission",
      "TemplateDefaultUserPermission",
    ],
    Timestamps: [
      "AiCompletionLog",
      "Contact",
      "Organization",
      "PetitionAccess",
      "PetitionFieldReply",
      "PetitionSignatureRequest",
      "PetitionUserGroupPermission",
      "PetitionUserPermission",
      "Profile",
      "ProfileType",
      "PublicPetition",
      "PublicPetitionFieldReply",
      "TemplateDefaultUserGroupPermission",
      "TemplateDefaultUserPermission",
      "User",
      "UserGroup",
    ],
    UserOrPetitionAccess: ["PetitionAccess", "User"],
    UserOrUserGroup: ["User", "UserGroup"],
  },
};
export default result;
