import { IntrospectionField, IntrospectionType } from "graphql";

export const supportMethods: {
  field: IntrospectionField;
  queryType: "mutation" | "query";
}[] = [
  {
    field: {
      name: "assignPetitionToUser",
      description: "Clones the petition and assigns the given user as owner and creator.",
      args: [
        {
          name: "petitionId",
          description: "Global ID of the petition",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "ID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "userId",
          description: "Global ID of the user",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "GID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "createOrganization",
      description: "Creates a new organization.",
      args: [
        {
          name: "email",
          description: "Email of the organization owner",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "firstName",
          description: "First name of the organization owner",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "lastName",
          description: "Last name of the organization owner",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "locale",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "PetitionLocale", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "name",
          description: "Name of the organization",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "password",
          description: "Temporary password of the organization owner",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "status",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "OrganizationStatus", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "createUser",
      description: "Creates a new user in the specified organization.",
      args: [
        {
          name: "email",
          description: "Email of the user",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "firstName",
          description: "First name of the user",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "lastName",
          description: "Last name of the user",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "locale",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "PetitionLocale", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "organizationId",
          description: "ID of the organization",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "password",
          description: "Temporary password of the user",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "role",
          description: "Role of the user",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "OrganizationRole", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "deletePetition",
      description: "Soft-deletes any given petition on the database.",
      args: [
        {
          name: "petitionId",
          description: "Global ID of the petition",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "ID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "getApiTokenOwner",
      description: "Get the user who owns an API Token",
      args: [
        {
          name: "token",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "globalIdDecode",
      description: "Decodes the given Global ID into an entity in the database.",
      args: [
        {
          name: "id",
          description: "Global ID to decode",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "ID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "query",
  },
  {
    field: {
      name: "globalIdEncode",
      description: "Encodes the given ID into a Global ID.",
      args: [
        {
          name: "id",
          description: "ID to encode",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "type",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "EntityType", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "query",
  },
  {
    field: {
      name: "resetSignaturitOrganizationBranding",
      description: "Removes the Signaturit Branding Ids of selected organization.",
      args: [
        {
          name: "orgId",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "resetUserPassword",
      description:
        "Resets the given user password on AWS Cognito and sends an email with new temporary.",
      args: [
        {
          name: "email",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "locale",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "PetitionLocale", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "shareSignaturitApiKey",
      description:
        "Shares our SignaturIt production APIKEY with the passed Org, and creates corresponding usage limits.",
      args: [
        {
          name: "limit",
          description: "How many credits allow the org to use in the given period",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "orgId",
          description: "Numeric ID of the Organization",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "period",
          description: "Period of the usage limit. e.g.: 1 month, 1 year, 20 days, etc...",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "transferOrganizationOwnership",
      description:
        "Transfers the ownership of an organization to a given user. Old owner will get ADMIN role",
      args: [
        {
          name: "organizationId",
          description: "Numeric ID of the organization",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "userId",
          description: "Global ID of the new owner",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "GID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "updateFeatureFlag",
      description: "Activate or deactivate an organization feature flag",
      args: [
        {
          name: "featureFlag",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "FeatureFlag", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "orgId",
          description: "Numeric ID of the organization",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "value",
          description: "Feature flag value",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Boolean", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "updateLandingTemplateMetadata",
      description: "Updates the metadata of a public landing template.",
      args: [
        {
          name: "backgroundColor",
          description: "for example: #A0FFCE",
          type: { kind: "SCALAR", name: "String", ofType: null },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "categories",
          description: "comma-separated list of categories",
          type: { kind: "SCALAR", name: "String", ofType: null },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "description",
          description: "short description for the template",
          type: { kind: "SCALAR", name: "String", ofType: null },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "image",
          description: null,
          type: { kind: "SCALAR", name: "Upload", ofType: null },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "slug",
          description: "must be URL-friendly",
          type: { kind: "SCALAR", name: "String", ofType: null },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "templateId",
          description: "global ID of the template",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "ID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "updateOrganizationLimits",
      description:
        "Updates the limits of a given org. If 'Update Current Period' is left unchecked, the changes will be reflected on the next period.",
      args: [
        {
          name: "amount",
          description: "How many credits allow the org to use in the given period",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "orgId",
          description: "Numeric ID of the Organization",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "period",
          description: "Period of the usage limit. e.g.: 1 month, 1 year, 20 days, etc...",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "String", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "type",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "ENUM", name: "OrganizationLimitType", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "updateCurrentPeriod",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Boolean", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "updateOrganizationUserLimit",
      description: "Updates the user limit for a organization",
      args: [
        {
          name: "limit",
          description: "How many users allow the org to create",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "orgId",
          description: "Numeric ID of the organization",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Int", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "updatePublicTemplateVisibility",
      description: "Updates template_public from template",
      args: [
        {
          name: "isPublic",
          description: "Public visiblity of template",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Boolean", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "templateId",
          description: "global ID of the template",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "GID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
  {
    field: {
      name: "uploadUserAvatar",
      description: "Uploads a user avatar image",
      args: [
        {
          name: "image",
          description: null,
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "Upload", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
        {
          name: "userId",
          description: "Global ID of the user",
          type: {
            kind: "NON_NULL",
            name: null,
            ofType: { kind: "SCALAR", name: "GID", ofType: null },
          },
          defaultValue: null,
          isDeprecated: false,
          deprecationReason: null,
        },
      ],
      type: {
        kind: "NON_NULL",
        name: null,
        ofType: { kind: "OBJECT", name: "SupportMethodResponse", ofType: null },
      },
      isDeprecated: false,
      deprecationReason: null,
    },
    queryType: "mutation",
  },
] as any;

export const schemaTypes: IntrospectionType[] = [
  {
    kind: "OBJECT",
    name: "SupportMethodResponse",
    description: "Return type for all support methods",
    specifiedByURL: null,
    fields: [
      {
        name: "message",
        description: null,
        args: [],
        type: { kind: "SCALAR", name: "String", ofType: null },
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "result",
        description: null,
        args: [],
        type: {
          kind: "NON_NULL",
          name: null,
          ofType: { kind: "ENUM", name: "Result", ofType: null },
        },
        isDeprecated: false,
        deprecationReason: null,
      },
    ],
    inputFields: null,
    interfaces: [],
    enumValues: null,
    possibleTypes: null,
  },
  {
    kind: "ENUM",
    name: "Result",
    description: "Represents the result of an operation.",
    specifiedByURL: null,
    fields: null,
    inputFields: null,
    interfaces: null,
    enumValues: [
      { name: "FAILURE", description: null, isDeprecated: false, deprecationReason: null },
      { name: "SUCCESS", description: null, isDeprecated: false, deprecationReason: null },
    ],
    possibleTypes: null,
  },
  {
    kind: "ENUM",
    name: "PetitionLocale",
    description: "The locale used for rendering the petition to the contact.",
    specifiedByURL: null,
    fields: null,
    inputFields: null,
    interfaces: null,
    enumValues: [
      { name: "en", description: null, isDeprecated: false, deprecationReason: null },
      { name: "es", description: null, isDeprecated: false, deprecationReason: null },
    ],
    possibleTypes: null,
  },
  {
    kind: "ENUM",
    name: "OrganizationStatus",
    description: "The status of the organization.",
    specifiedByURL: null,
    fields: null,
    inputFields: null,
    interfaces: null,
    enumValues: [
      {
        name: "ACTIVE",
        description: "Used for regular clients",
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "CHURNED",
        description: "Used on churned clients",
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "DEMO",
        description: "Used for demoing the product",
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "DEV",
        description: "Used for development or testing purposes",
        isDeprecated: false,
        deprecationReason: null,
      },
      { name: "ROOT", description: "Root client", isDeprecated: false, deprecationReason: null },
    ],
    possibleTypes: null,
  },
  {
    kind: "ENUM",
    name: "OrganizationRole",
    description: "The roles of a user within an organization.",
    specifiedByURL: null,
    fields: null,
    inputFields: null,
    interfaces: null,
    enumValues: [
      { name: "ADMIN", description: null, isDeprecated: false, deprecationReason: null },
      { name: "COLLABORATOR", description: null, isDeprecated: false, deprecationReason: null },
      { name: "NORMAL", description: null, isDeprecated: false, deprecationReason: null },
      { name: "OWNER", description: null, isDeprecated: false, deprecationReason: null },
    ],
    possibleTypes: null,
  },
  {
    kind: "ENUM",
    name: "EntityType",
    description: null,
    specifiedByURL: null,
    fields: null,
    inputFields: null,
    interfaces: null,
    enumValues: [
      { name: "Contact", description: null, isDeprecated: false, deprecationReason: null },
      { name: "Organization", description: null, isDeprecated: false, deprecationReason: null },
      { name: "Petition", description: null, isDeprecated: false, deprecationReason: null },
      { name: "User", description: null, isDeprecated: false, deprecationReason: null },
    ],
    possibleTypes: null,
  },
  {
    kind: "ENUM",
    name: "FeatureFlag",
    description: null,
    specifiedByURL: null,
    fields: null,
    inputFields: null,
    interfaces: null,
    enumValues: [
      { name: "DEVELOPER_ACCESS", description: null, isDeprecated: false, deprecationReason: null },
      {
        name: "EXPORT_CUATRECASAS",
        description: null,
        isDeprecated: false,
        deprecationReason: null,
      },
      { name: "GHOST_LOGIN", description: null, isDeprecated: false, deprecationReason: null },
      {
        name: "HIDE_RECIPIENT_VIEW_CONTENTS",
        description: null,
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "INTERNAL_COMMENTS",
        description: null,
        isDeprecated: false,
        deprecationReason: null,
      },
      { name: "ON_BEHALF_OF", description: null, isDeprecated: false, deprecationReason: null },
      {
        name: "PETITION_PDF_EXPORT",
        description: null,
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "PETITION_SIGNATURE",
        description: null,
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "REMOVE_WHY_WE_USE_PARALLEL",
        description: null,
        isDeprecated: false,
        deprecationReason: null,
      },
      {
        name: "SKIP_FORWARD_SECURITY",
        description: null,
        isDeprecated: false,
        deprecationReason: null,
      },
    ],
    possibleTypes: null,
  },
  {
    kind: "ENUM",
    name: "OrganizationLimitType",
    description: null,
    specifiedByURL: null,
    fields: null,
    inputFields: null,
    interfaces: null,
    enumValues: [
      { name: "PETITIONS", description: null, isDeprecated: false, deprecationReason: null },
      { name: "SIGNATURES", description: null, isDeprecated: false, deprecationReason: null },
    ],
    possibleTypes: null,
  },
] as any;
