export const BACKGROUND_CHECK_TOPICS = {
  crime: "Crime",
  "crime.fraud": "Fraud",
  "crime.cyber": "Cybercrime",
  "crime.fin": "Financial crime",
  "crime.env": "Environmental violations",
  "crime.theft": "Theft",
  "crime.war": "War crimes",
  "crime.boss": "Criminal leadership",
  "crime.terror": "Terrorism",
  "crime.traffick": "Trafficking",
  "crime.traffick.drug": "Drug trafficking",
  "crime.traffick.human": "Human trafficking",
  "corp.offshore": "Offshore",
  "corp.shell": "Shell company",
  "corp.public": "Public listed company",
  gov: "Government",
  "gov.national": "National government",
  "gov.state": "State government",
  "gov.muni": "Municipal government",
  "gov.soe": "State-owned enterprise",
  "gov.igo": "Intergovernmental organization",
  "gov.head": "Head of government or state",
  "gov.admin": "Civil service",
  "gov.executive": "Executive branch of government",
  "gov.legislative": "Legislative branch of government",
  "gov.judicial": "Judicial branch of government",
  "gov.security": "Security services",
  "gov.financial": "Central banking and financial integrity",
  fin: "Financial services",
  "fin.bank": "Bank",
  "fin.fund": "Fund",
  "fin.advisor": "Financial advisor",
  "role.rca": "Close Associate",
  "role.judge": "Judge",
  "role.civil": "Civil servant",
  "role.diplo": "Diplomat",
  "role.lawyer": "Lawyer",
  "role.acct": "Accountant",
  "role.spy": "Spy",
  "role.oligarch": "Oligarch",
  "role.journo": "Journalist",
  "role.act": "Activist",
  "pol.party": "Political party",
  "pol.union": "Union",
  rel: "Religion",
  mil: "Military",
  "asset.frozen": "Frozen asset",
  sanction: "Sanctioned entity",
  "sanction.linked": "Sanction-linked entity",
  "export.control": "Export controlled",
  debarment: "Debarred entity",
  poi: "Person of interest",
  wanted: "Wanted",
  "corp.disqual": "Disqualified",
  "reg.action": "Regulator action",
  "reg.warn": "Regulator warning",
  "role.pol": "Non-PEP",
  "role.pep": "Politician", // update of "Political"
  "role.lobby": "Lobbyist",
  "sanction.counter": "Counter-sanctioned entity",
  "export.risk": "Trade risk",
} as Record<string, string>;
