import { PetitionFieldType } from "@parallel/graphql/__types";

export function getPetitionFieldTypeKeywords(type: PetitionFieldType) {
  switch (type) {
    case "FILE_UPLOAD":
      return [
        "files",
        "upload",
        "documents",
        "pdf",
        "annexes",
        "attachment",
        "adjuntar",
        "documentos",
        "subir",
        "anexos",
        "adjuntos",
        "archivos",
        "imágenes",
        "images",
      ];
    case "SHORT_TEXT":
      return [
        "texto",
        "text",
        "escribir",
        "write",
        "corto",
        "short",
        "account",
        "cuenta",
        "pasaporte",
        "passport",
        "email",
        "correo",
        "electrónico",
        "iban",
        "address",
        "dirección",
        "description",
        "descripción",
        "name",
        "nombre",
        "url",
        "website",
        "webpage",
        "página web",
        "dni/nie",
        "national",
        "postal code",
        "código postal",
        "zip",
        "nif",
        "tax",
        "id",
        "iban",
        "social security",
        "seguridad social",
      ];
    case "TEXT":
      return [
        "long",
        "largo",
        "dirección",
        "address",
        "write",
        "escribir",
        "textarea",
        "description",
        "descripción",
        "comments",
        "comentarios",
        "notes",
        "notas",
      ];
    case "NUMBER":
      return [
        "amount",
        "cantidad",
        "quantity",
        "cantidades",
        "quantities",
        "total",
        "total",
        "price",
        "precio",
        "discount",
        "descuento",
        "percentages",
        "porcentajes",
        "rate",
        "tasa",
        "interest",
        "interés",
        "tax",
        "impuesto",
        "números",
        "numbers",
      ];
    case "PHONE":
      return [
        "phone",
        "teléfono",
        "number",
        "número",
        "mobile",
        "móvil",
        "cell",
        "celular",
        "call",
        "llamar",
        "contact",
        "contacto",
        "contactar",
      ];
    case "HEADING":
      return [
        "help",
        "ayuda",
        "instructions",
        "instrucciones",
        "notes",
        "notas",
        "title",
        "título",
        "cláusula",
        "párrafo",
        "clause",
        "paragraph",
        "salto de página",
        "page break",
        "encabezado",
        "heading",
        "header",
        "texto",
        "text",
        "sección",
        "section",
      ];
    case "SELECT":
      return [
        "list of",
        "countries",
        "country",
        "EU",
        "non-EU",
        "currencies",
        "listado",
        "países",
        "ue",
        "divisas",
        "monedas",
      ];
    case "DYNAMIC_SELECT":
      return [
        "opciones",
        "elegir",
        "desplegable múltiple",
        "encadenar",
        "escoger",
        "selección",
        "options",
        "choices",
        "select",
        "multiple",
        "chain",
      ];
    case "CHECKBOX":
      return [
        "options",
        "multiple",
        "choice",
        "choices",
        "casillas",
        "selection",
        "opciones",
        "múltiple respuesta",
        "multiple choice",
        "escoger",
        "choose",
        "radio button",
        "elección",
        "elecciones",
        "selección",
      ];
    case "DATE":
      return [
        "día",
        "day",
        "month",
        "mes",
        "year",
        "año",
        "date",
        "fecha",
        "birth",
        "nacimiento",
        "expiration",
        "caducidad",
        "start",
        "inicio",
        "end",
        "fin",
        "due",
        "vencimiento",
        "deadline",
        "plazo",
        "delivery",
        "entrega",
      ];
    case "DATE_TIME":
      return [
        "date",
        "fecha",
        "time",
        "hora",
        "start",
        "inicio",
        "end",
        "fin",
        "due",
        "vencimiento",
        "deadline",
        "plazo",
        "delivery",
        "entrega",
      ];
    case "ES_TAX_DOCUMENTS":
      return [
        "documentos oficiales",
        "official documents",
        "spanish",
        "agencia tributaria",
        "tax return",
        "vat",
        "tax",
        "documents",
        "official",
        "aeat",
        "seguridad social",
        "dgt",
        "tráfico",
        "renta",
        "irpf",
        "declaración",
        "vida laboral",
        "catastro",
        "036",
        "iva",
        "social security",
        "impuestos",
        "documentos",
      ];
    case "DOW_JONES_KYC":
      return [];
    case "BACKGROUND_CHECK":
      return [
        "sanctions",
        "PEPs",
        "background",
        "screening",
        "check",
        "research",
        "sanciones",
        "antecedentes",
        "comprobación",
        "investigación",
        "persona expuesta políticamente",
        "politically exposed person",
        "relaciones",
        "relationships",
        "político",
      ];
    case "FIELD_GROUP":
      return [
        "identificar",
        "identify",
        "propiedades",
        "properties",
        "party",
        "agrupar",
        "parte",
        "contacto",
        "contact",
        "group",
        "profile",
        "multiple",
        "fields",
        "perfil",
        "múltiples",
        "campos",
        "grupo",
      ];
    case "ID_VERIFICATION":
      return ["id", "dni"];
    case "PROFILE_SEARCH":
      return [
        "search",
        "buscar",
        "búsqueda",
        "buscar",
        "perfil",
        "profile",
        "person",
        "people",
        "conflict",
      ];
    case "ADVERSE_MEDIA_SEARCH":
      return ["adverse", "media", "search", "búsqueda", "medio", "adverso", "noticia", "news"];
    default:
      throw new Error(`Missing keywords PetitionFieldType  "${type}"`);
  }
}
