import { ContainerModule } from "inversify";
import { ANALYTICS, AnalyticsService, IAnalyticsService } from "./analytics";
import { AUTH, Auth, IAuth } from "./auth";
import { Aws, AWS_SERVICE, IAws } from "./aws";
import { EMAILS, EmailsService, IEmailsService } from "./emails";
import { FetchService, FETCH_SERVICE, IFetchService } from "./fetch";
import { I18nService, I18N_SERVICE, II18nService } from "./i18n";
import { IImageService, ImageService, IMAGE_SERVICE } from "./image";
import { createLogger, ILogger, LOGGER } from "./logger";
import { IPetitionBinder, PetitionBinder, PETITION_BINDER } from "./petition-binder";
import { IPrinter, Printer, PRINTER } from "./printer";
import { IRedis, REDIS, Redis } from "./redis";
import { ISignatureService, SIGNATURE, SignatureService } from "./signature";
import { ISmtp, Smtp, SMTP } from "./smtp";
import { IStorage, StorageService, STORAGE_SERVICE } from "./storage";
import { ITiersService, TiersService, TIERS_SERVICE } from "./tiers";

export const servicesModule = new ContainerModule((bind) => {
  bind<ILogger>(LOGGER).toDynamicValue(createLogger).inSingletonScope();
  bind<IAuth>(AUTH).to(Auth);
  bind<IAws>(AWS_SERVICE).to(Aws).inSingletonScope();
  bind<IEmailsService>(EMAILS).to(EmailsService);
  bind<IAnalyticsService>(ANALYTICS).to(AnalyticsService).inSingletonScope();
  bind<IRedis>(REDIS).to(Redis).inSingletonScope();
  bind<ISmtp>(SMTP).to(Smtp).inSingletonScope();
  bind<IPrinter>(PRINTER).to(Printer);
  bind<ISignatureService>(SIGNATURE).to(SignatureService);
  bind<IStorage>(STORAGE_SERVICE).to(StorageService);
  bind<IFetchService>(FETCH_SERVICE).to(FetchService).inSingletonScope();
  bind<IImageService>(IMAGE_SERVICE).to(ImageService).inSingletonScope();
  bind<IPetitionBinder>(PETITION_BINDER).to(PetitionBinder);
  bind<ITiersService>(TIERS_SERVICE).to(TiersService);
  bind<II18nService>(I18N_SERVICE).to(I18nService).inSingletonScope();
});
