import { ContainerModule } from "inversify";
import { AppsumoActivateAccountEmailBuilder } from "./AppsumoActivateAccountEmailBuilder";
import { BackgroundCheckMonitoringChangesEmailBuilder } from "./BackgroundCheckMonitoringChangesEmailBuilder";
import { CommentsContactNotificationEmailBuilder } from "./CommentsContactNotificationEmailBuilder";
import { CommentsUserNotificationEmailBuilder } from "./CommentsUserNotificationEmailBuilder";
import { ContactAuthenticationRequestEmailBuilder } from "./ContactAuthenticationRequestEmailBuilder";
import { DeveloperWebhookFailedEmailBuilder } from "./DeveloperWebhookFailedEmailBuilder";
import { InternalSignaturitAccountDepletedCreditsEmailBuilder } from "./InternalSignaturitAccountDepletedCreditsEmailBuilder";
import { InvitationEmailBuilder } from "./InvitationEmailBuilder";
import { OrganizationLimitsReachedEmailBuilder } from "./OrganizationLimitsReachedEmailBuilder";
import { PetitionAccessDelegatedEmailBuilder } from "./PetitionAccessDelegatedEmailBuilder";
import { PetitionApprovalRequestStepCanceledEmailBuilder } from "./PetitionApprovalRequestStepCanceledEmailBuilder";
import { PetitionApprovalRequestStepFinishedEmailBuilder } from "./PetitionApprovalRequestStepFinishedEmailBuilder";
import { PetitionApprovalRequestStepPendingEmailBuilder } from "./PetitionApprovalRequestStepPendingEmailBuilder";
import { PetitionClosedNotificationEmailBuilder } from "./PetitionClosedNotificationEmailBuilder";
import { PetitionCompletedEmailBuilder } from "./PetitionCompletedEmailBuilder";
import { PetitionMessageBouncedEmailBuilder } from "./PetitionMessageBouncedEmailBuilder";
import { PetitionMessageEmailBuilder } from "./PetitionMessageEmailBuilder";
import { PetitionReminderEmailBuilder } from "./PetitionReminderEmailBuilder";
import { PetitionSharedEmailBuilder } from "./PetitionSharedEmailBuilder";
import { ProfilesExpiringPropertiesEmailBuilder } from "./ProfilesExpiringPropertiesEmailBuilder";
import { PublicPetitionLinkAccessEmailBuilder } from "./PublicPetitionLinkAccessEmailBuilder";
import { SendFromDatabaseEmailBuilder } from "./SendFromDatabaseEmailBuilder";
import { SignatureCancelledDeclinedBySignerEmailBuilder } from "./SignatureCancelledDeclinedBySignerEmailBuilder";
import { SignatureCancelledNoCreditsLeftEmailBuilder } from "./SignatureCancelledNoCreditsLeftEmailBuilder";
import { SignatureCancelledRequestErrorEmailBuilder } from "./SignatureCancelledRequestErrorEmailBuilder";
import { TransferParallelsEmailBuilder } from "./TransferParallelsEmailBuilder";

export const emailBuildersModule = new ContainerModule((options) => {
  options.bind(PetitionCompletedEmailBuilder).toSelf();
  options.bind(CommentsUserNotificationEmailBuilder).toSelf();
  options.bind(CommentsContactNotificationEmailBuilder).toSelf();
  options.bind(PetitionMessageEmailBuilder).toSelf();
  options.bind(PetitionReminderEmailBuilder).toSelf();
  options.bind(PetitionSharedEmailBuilder).toSelf();
  options.bind(PetitionClosedNotificationEmailBuilder).toSelf();
  options.bind(PetitionMessageBouncedEmailBuilder).toSelf();
  options.bind(ContactAuthenticationRequestEmailBuilder).toSelf();
  options.bind(PetitionAccessDelegatedEmailBuilder).toSelf();
  options.bind(DeveloperWebhookFailedEmailBuilder).toSelf();
  options.bind(PublicPetitionLinkAccessEmailBuilder).toSelf();
  options.bind(OrganizationLimitsReachedEmailBuilder).toSelf();
  options.bind(AppsumoActivateAccountEmailBuilder).toSelf();
  options.bind(InternalSignaturitAccountDepletedCreditsEmailBuilder).toSelf();
  options.bind(SignatureCancelledNoCreditsLeftEmailBuilder).toSelf();
  options.bind(SignatureCancelledRequestErrorEmailBuilder).toSelf();
  options.bind(SignatureCancelledDeclinedBySignerEmailBuilder).toSelf();
  options.bind(InvitationEmailBuilder).toSelf();
  options.bind(SendFromDatabaseEmailBuilder).toSelf();
  options.bind(TransferParallelsEmailBuilder).toSelf();
  options.bind(ProfilesExpiringPropertiesEmailBuilder).toSelf();
  options.bind(BackgroundCheckMonitoringChangesEmailBuilder).toSelf();
  options.bind(PetitionApprovalRequestStepPendingEmailBuilder).toSelf();
  options.bind(PetitionApprovalRequestStepFinishedEmailBuilder).toSelf();
  options.bind(PetitionApprovalRequestStepCanceledEmailBuilder).toSelf();
});
